- name: Run "show version" & "show interfaces" on remote nodes.
  cisco.ios.ios_command:
    commands:
      - show version
      - show interfaces
  register: info_

- name: Gather config legacy facts
  cisco.ios.ios_facts:
    gather_subset: 
    - config                        # You can replace this by : [config, default, hardware, interfaces, all]
  register: config_

- name: Gather hardware legacy facts
  cisco.ios.ios_facts:
    gather_subset: 
    - hardware
  register: hardware_  

- name: Gather interfaces legacy facts
  cisco.ios.ios_facts:
    gather_subset: 
    - interfaces
  register: interfaces_ 

- name: Show info results
  debug:
     var: info_

- name: Show config results
  debug:
     var: config_

- name: Show hardware results
  debug:
     var: hardware_

- name: Show interfaces results
  debug:
     var: interfaces_

- name: Show the hostname
  debug:
     msg: "The name of the hostname is : {{ ansible_net_hostname }}"

- name: Show the IpV4 information
  debug:
     msg: "The Ip of this machine is : {{ ansible_net_all_ipv4_addresses }}"

- include_tasks: show_mac.yml
- include_tasks: show_run.yml
