- name: Get the Running config
  ios_command:
    commands:
      - show run
  tags: show_run
  register: show_output
  ignore_errors: true

- name: Display the command output
  debug:
    var: show_output
  tags: show_run
