- name: Configure banner
  cisco.ios.ios_banner:
    banner: motd
    text: "{{ BANNER_TEXT }}"  # Set your Banner here !
    state: present

- name: Configure the login banner
  cisco.ios.ios_banner:
    banner: login
    text: | "{{ LOGIN_BANNER_TEXT }}"  # Set your Login Banner here !
    state: present
