- name: Enable and Add description do Interfaces
  cisco.ios.ios_interfaces:
    config:
      - name: FastEthernet0/0
      # For my config : "FastEthernet0/0" is for my Routers and "GigabitEthernet0/0" is for my switch.
      # If i want my config to be deployed on my swith i need to replace "FastEthernet0/0" by "GigabitEthernet0/0".
        description: Configured by Artemiss
        enabled: true
