- name: Configure the Users
  ios_config:
    lines:
    - username {{ CISCO_USER }} password {{ CISCO_PASS }}

- name: Enable password configuration
  ios_config:
    lines: 
    - enable secret {{ CISCO_SECRET }}

- name: Encrypt the passwords
  ios_config:
    lines:
    - service password-encryption

- name: Configure the SCP User
  ios_config:
    lines:
    - username scp privilege 15 password {{ CISCO_SCP_PASS }}

- name: Enable scp server
  ios_config:
    lines: ip scp server enable 
