- name: Enable and Add description to Interfaces on Routers
  cisco.ios.ios_interfaces:
    config:
      - name: "{{ ROUTERS_INT }}" # Replace this by the interface you want to configure.
       # For the Routers : The Switch will make an error.
        description: Routers Configured by Artemiss
        enabled: true
  ignore_errors: true

- name: Enable and Add description to Interfaces on Switch
  cisco.ios.ios_interfaces:
    config:
      - name: "{{ SWITCH_INT }}" # Replace this by the interface you want to configure.
      # For the Switch : The Routers will make an error.
        description: Switch Configured by Artemiss
        enabled: true
  ignore_errors: true
