---

- name: Configure Hostname
  ios_config:
    lines: hostname {{ inventory_hostname }}

- name: Configure Domain Name
  ios_system:
    domain_name: ansible.local

- name: Configure DNS lookup sources
  ios_system:
    lookup_enabled: yes

- include_tasks: conf_interfaces
- include_tasks: conf_banner
- include_tasks: conf_security

- name: Save the Configuration
  ios_config:
    save_when: changed
