---
- name: Include the variables
  ansible.builtin.include_vars: /etc/ansible/roles/Learning-Ansible/Cisco_Switch/VARS.yml

- name: Configure Hostname
  ios_config:
    lines: hostname {{ inventory_hostname }}

- name: Configure Domain Name
  ios_system:
    domain_name: "{{ DOMAIN }}"

- name: Configure DNS lookup sources
  ios_system:
    lookup_enabled: yes

- include_tasks: conf_interfaces.yml
- include_tasks: conf_banner.yml
- include_tasks: conf_security.yml

- name: Save the Configuration
  ios_config:
    save_when: changed
