---

- name: Configure Hostname
  ios_config:
    lines: hostname {{ inventory_hostname }}

- name: Configure Domain Name
  ios_system:
    domain: ansible.local

- name: Configure DNS lookup sources
  ios_system:
    lookup_enabled: yes

- name: Configure banner
  cisco.ios.ios_banner:
    banner: motd
    text: "ACCESS NOT ALLOWED ! | This router is properties of Artemiss !"
    state: present

- name: Configure the login banner
  cisco.ios.ios_banner:
    banner: login
    text: |
      Banner of Login
      Please Register
    state: present

- name: Configure the Users
  ios_config:
    lines:
    - username admin password admin

- name: "Enable" password configuration
  ios_config:
    lines: 
    - enable secret hello

- name: Encrypt the passwords
  ios_config:
    lines:
    - service password-encryption

- name: Configure SSH Version 2
  ios_config:
    lines:
    - ip ssh version 2


- name: Save the Configuration
  ios_config:
    save_when: changed