
#-----------------------------#PACKAGES-PROMPT#-----------------------------#
    - name: PACKAGE
      pause:
        prompt: "[???] Would you like to update packages or install new one ? (update/install)"
      register: PACKAGE_TYPE_CHOICE
#-----------------------------#PACKAGES-PROMPT#-----------------------------#

#-----------------------------#PACKAGES-PROMPT#-----------------------------#
    - name: PACKAGE
      pause:
        prompt: "[???] How would you like your installation to be? ? (interactive/customized)"
      register: PACKAGE_INSTALLATION_TYPE_CHOICE
#-----------------------------#PACKAGES-PROMPT#-----------------------------#

#-----------------------------#PACKAGES#-----------------------------#
    - include_tasks: prerequisites.yml
    - include_tasks: package_ask.yml
    - include_tasks: package_list.yml
#-----------------------------#PACKAGES#-----------------------------#
