#-----------------------------#FACTS#-----------------------------#
    - include_tasks: prerequisites.yml
#-----------------------------#FACTS#-----------------------------#

#-----------------------------#PACKAGES#-----------------------------#
    - include_tasks: package_list.yml
#-----------------------------#PACKAGES#-----------------------------#
