
#-----------------------------#PACKAGES-PROMPT#-----------------------------#

#-----------------------------#PACKAGES-PROMPT#-----------------------------#

#-----------------------------#PACKAGES#-----------------------------#
    - include_tasks: prerequisites.yml
    - include_tasks: package_ask.yml
    - include_tasks: package_list.yml
#-----------------------------#PACKAGES#-----------------------------#
