- name: INFORMATION
  debug:
      msg: "Installing packages..."
      
- name: Install Web Browser
  ansible.windows.win_package:
    path: https://www.7-zip.org/a/7z2404-x64.exe
    product_id: Z-zip
    arguments: /install /passive /norestart
  when: ZZIP_CHOICE.user_input | bool
