#- name: Install the package
#  win_chocolatey:
#    name: "{{ PACKAGE_INSTALL_CHOICE.user_input }}"
#  when: PACKAGE_INSTALL_CHOICE is defined

- name: Install the packages
  win_chocolatey:
    name: "{{ item }}"
  loop: "{{ packages_list }}"
  when: PACKAGE_INSTALL_CHOICE is defined

- name: PACKAGE
  pause:
    prompt: "[???] Do you want to add other packages ?"
  register: PACKAGE_REASK_CHOICE

- include_tasks: package_ask_customized.yml
  when: PACKAGE_REASK_CHOICE is defined and PACKAGE_REASK_CHOICE.user_input | bool
