
- name: Install Web Browser via Chocolatey
  win_chocolatey:
    name: "{{ WEB_BROWSER_CHOICE.user_input }}"
    state: present
  when: WEB_BROWSER_CHOICE is defined and WEB_BROWSER_CHOICE.user_input in ["firefox", "googlechrome", "opera"]

- name: INFORMATION
  debug:
      msg: "Installing some usefull packages..."

- name: Install Zzip
  win_chocolatey:
    name: 7zip
    state: present
  when: 7ZIP_CHOICE.user_input | bool

- name: Install Putty
  win_chocolatey:
    name: putty
    state: present
  when: PUTTY_CHOICE.user_input | bool

- name: Install VScode
  win_chocolatey:
    name: vscode
    state: present
  when: VSCODE_CHOICE.user_input | bool

- name: Install Malwarebytes
  win_chocolatey:
    name: malwarebytes
    state: present
  when: MALWAREBYTES_CHOICE.user_input | bool

- name: Install VLC media player 
  win_chocolatey:
    name: vlc
    state: present
  when: VLC_CHOICE.user_input | bool

- name: Install Audacity
  win_chocolatey:
    name: audacity
    state: present
