#-----------------------------------HELP-----------------------------------#
- name: PACKAGE
  pause:
    prompt: "[???] Do you want to see a list of package ? (yes/no)"
  register: PACKAGE_COOL_LIST

- include_tasks: package_list_help.yml
  when: PACKAGE_COOL_LIST.user_input | bool
#-----------------------------------HELP-----------------------------------#

- name: PACKAGE
  pause:
    prompt: "[???] Which package(s) would you like to install (separate multiple packages with a comma)?"
  register: PACKAGE_INSTALL_CHOICE

- set_fact:
    PACKAGE_LIST: "{{ PACKAGE_INSTALL_CHOICE.user_input.split(',') }}"
