
- name: Install the packages
  win_chocolatey:
    name: "{{ item }}"
  loop: "{{ PACKAGE_LIST }}"
  when: PACKAGE_INSTALL_CHOICE is defined

- name: PACKAGE
  pause:
    prompt: "[???] Do you want to add other packages ? (yes/no)"
  register: PACKAGE_REASK_CHOICE

- include_tasks: main.yml
  when: PACKAGE_REASK_CHOICE is defined and PACKAGE_REASK_CHOICE.user_input | bool
