#########################################GATHER#########################################
  - name: Gather IOS type facts
    cisco.ios.ios_facts:
      gather_subset: hardware
#########################################GATHER#########################################

########################################KEEPING-MACHINE-TYPE#########################################
  - name: Keeping machine type in var
    set_fact:
      MACHINE_TYPE: "ROUTER"
    when: (ansible_net_model == "3725") or
          (ansible_net_model == "4000") or
          (ansible_net_model == "2900") or
          (ansible_net_model == "1900") or
          (ansible_net_model == "800") or
          (ansible_net_model == "7200") or
          (ansible_net_model == "3800") or
          (ansible_net_model == "1800")

  - name: Keeping machine type in var
    set_fact:
      MACHINE_TYPE: "SWITCH"
    when: (ansible_net_model == "IOSv") or
          (ansible_net_model == "9000") or
          (ansible_net_model == "3850") or
          (ansible_net_model == "3650") or
          (ansible_net_model == "9000") or
          (ansible_net_model == "7000") or
          (ansible_net_model == "5000") or
          (ansible_net_model == "9300") or
          (ansible_net_model == "2960") or 
          (ansible_net_model == "3560") or 
          (ansible_net_model == "3750") or 
          (ansible_net_model == "3850")    

########################################KEEPING-MACHINE-TYPE#########################################

########################################LAYER-TYPE#########################################
  - name: Gather version information
    cisco.ios.ios_command:
      commands: show version
    register: version_
########################################LAYER-TYPE#########################################

########################################INFORMATION#########################################
  - name: IOS
    debug:
       msg: "Your machine is a {{ MACHINE_TYPE }} with model type {{ ansible_net_model }}."

  - name: IOS # Switch Layer 3
    debug:
       msg: "This machine is a Switch Layer 3 ! (L3)"
    when: (MACHINE_TYPE == "SWITCH") and
          ('l3' in version_ | lower)

  - name: IOS # Switch Layer 2
    debug:
       msg: "This machine is a Switch Layer 2 ! (L2)"
    when: (MACHINE_TYPE == "SWITCH") and
          ('l2' in version_ | lower)
########################################INFORMATION#########################################
