#########################################GATHER#########################################
  - name: Gather IOS type facts
    cisco.ios.ios_facts:
      gather_subset: hardware
#########################################GATHER#########################################

########################################INFORMATION#########################################
  - name: PRINT IOS TYPE
    debug:
       msg: "Your IOS Type is {{ ansible_net_iostype }} !"
########################################INFORMATION#########################################

########################################KEEPING-MACHINE-TYPE#########################################
  - name: Keeping machine type in var
    set_fact:
      MACHINE_TYPE: "ROUTER"
    when: (ansible_net_model == "3725") or
          (ansible_net_model == "4000") or
          (ansible_net_model == "2900") or
          (ansible_net_model == "1900") or
          (ansible_net_model == "800") or
          (ansible_net_model == "7200") or
          (ansible_net_model == "3800") or
          (ansible_net_model == "1800")

  - name: Keeping machine type in var
    set_fact:
      MACHINE_TYPE: "SWITCH"
    when: (ansible_net_model == "IOSv") or
          (ansible_net_model == "9000") or
          (ansible_net_model == "3850") or
          (ansible_net_model == "3650") or
          (ansible_net_model == "9000") or
          (ansible_net_model == "7000") or
          (ansible_net_model == "5000") or
          (ansible_net_model == "9300")
########################################KEEPING-MACHINE-TYPE#########################################

########################################INFORMATION#########################################
  - name: IOS
    debug:
       msg: "Your machine is a {{ MACHINE_TYPE }} with model type {{ ansible_net_model }}."

########################################INFORMATION#########################################

  - name: IOS TEST
    debug:
       var: ansible_net_gather_subset

