- name: Gather IOS type facts
  cisco.ios.ios_facts:
    gather_subset: hardware


  - name: PRINT IOS TYPE
    debug:
       msg: "This role will collect information about {{ ansible_net_iostype }} to help you !"

