- name: INFORMATION
  debug:
      msg: "Starting to update..."

- name: Create directory Updates structure
  ansible.windows.win_file:
    path: C:\Updates
    state: directory

- name: Search-only, return list of found updates (if any), log to C:\Updates\latest_updates_result.txt
  ansible.windows.win_updates:
    state: searched
    log_path: C:\Updates\latest_updates_result.txt
  register: list_found_updates

- name: Show list of found updates
  debug:
      var: list_found_updates

- name: Install all updates
  ansible.windows.win_updates:
    category_names: '*'
    reboot: false
  register: installation_updates

- name: Show result of installation
  debug:
      var: installation_updates
