- name: INFORMATION
  debug:
      msg: "Starting to update..."

- name: Search-only, return list of found updates (if any), log to C:\ansible_wu.txt
  ansible.windows.win_updates:
    state: searched
    log_path: C:\Updates\latest_updates_result.txt
  register: list_found_updates

- name: Show list of found updates
  debug:
      var: list_found_updates
