#-----------------------------#CHECK-CONTAINERS#-----------------------------#
- name: Vérifier les conteneurs Docker existants
  command: docker ps -a
  register: docker_containers

- name: Afficher les conteneurs Docker existants
  debug:
    var: docker_containers.stdout
#-----------------------------#CHECK-CONTAINERS#-----------------------------#

#-----------------------------#CHECK-IMAGES#-----------------------------#
- name: Vérifier les images Docker existantes
  command: docker images
  register: docker_images

- name: Afficher les images Docker existantes
  debug:
    var: docker_images.stdout
#-----------------------------#CHECK-IMAGES#-----------------------------#

- name: Get info on docker host and list images
  community.docker.docker_host_info:
    images: true
  register: result

- name: Show host information
  ansible.builtin.debug:
    var: result.host_info
