- name: Vérifier les conteneurs Docker existants
  command: docker ps -a
  register: docker_containers

- name: Afficher les conteneurs Docker existants
  debug:
    var: docker_containers.stdout
###STACK###
- name: Shows stack info
  community.docker.docker_stack_info:
  register: result

- name: Show results
  ansible.builtin.debug:
    var: result.results
###STACK###
