- name: Vérifier les conteneurs Docker existants
  command: docker ps -a
  register: docker_containers

- name: Afficher les conteneurs Docker existants
  debug:
    var: docker_containers.stdout

- name: Vérifier les images Docker existantes
  command: docker images
  register: docker_images

- name: Afficher les images Docker existantes
  debug:
    var: docker_images.stdout
