---
- hosts: CISCO
#  gather_facts: no
  become: yes
  vars_prompt:
    - name: "test_connectivity"
      prompt: "[???] Do you want to test the connection (yes/no) ?"
      private: no

  tasks:
    - include_tasks: ./roles/connectivity_test/tasks/main.yml
      when: test_connectivity | bool

    - include_tasks: ./roles/debug/tasks/main.yml
