---
- hosts: CISCO
  become: yes
  vars_prompt:
    - name: "test_connectivity"
      prompt: "[???] Do you want to test the connection (yes/no) ?"
      private: no

  tasks:
    - include_tasks: /etc/ansible/roles/Learning-Ansible/Cisco_Switch/roles/connectivity_test/tasks/main.yml
      when: test_connectivity | bool

    - include_tasks: /etc/ansible/roles/Learning-Ansible/Cisco_Switch/roles/debug/tasks/main.yml
