---
- hosts: Routers
  become: yes
  vars_prompt:

    - name: DOMAIN
      prompt: [???] What domain would you like to set ?
      default: "ansible.lan"
      private: false

    - name: HOSTNAME
      prompt: [???] What hostname would you like to set ?
      default: {{ inventory_hostname }}
      private: false


  roles:
    - connectivity_test
