---
- hosts: R1
  gather_facts: no
  become: yes

  tasks:
  
    - include_tasks: /etc/ansible/roles/Learning-Ansible/Cisco_Switch/roles/RouterConfig/get_info/tasks/main.yml
    
    - include_tasks: /etc/ansible/roles/Learning-Ansible/Cisco_Switch/roles/RouterConfig/conf_base/tasks/main.yml
