- name: DynFi-Manager | Choose the download location
  pause:
    prompt: "[???] Where do you want to download the script ? (example : /etc/ansible)"
  register: DOWNLOAD_LOCATION

- name: Download the DynFi Manager file
  get_url:
    url: "https://dynfi.com/scripts/DynFi_Manager_Installer.sh.tgz"
    dest: "{{ DOWNLOAD_LOCATION.user_input }}/DynFi_Manager_Installer.sh.tgz"
    mode: '0644'
