- name: Extract the tgz archive
  unarchive:
    src: "{{ DOWNLOAD_LOCATION.user_input }}/DynFi_Manager_Installer.sh.tgz"
    dest: "{{ DOWNLOAD_LOCATION.user_input }}/"
    remote_src: yes
    mode: '0755'

- name: Change the permissions of the script
  file:
    path: "{{ DOWNLOAD_LOCATION.user_input }}/DynFi_Manager_Installer.sh"
    mode: '0755'
