- name: Run the DynFi Manager script
  expect:
    command: "{{ DOWNLOAD_LOCATION.user_input }}/DynFi_Manager_Installer.sh"
    responses:
      "Voulez-vous continuer ?": "yes\n"  # Exemple de réponse à un prompt
      "Saisissez votre nom :": "ansible\n"  # Exemple de réponse à un autre prompt
    echo: yes
