---
  - name: List of Interfaces
    debug:
      var: interfaces_

  - name: Display all interfaces names
    ansible.builtin.debug:
      var: interfaces_
    loop: "{{ interfaces_definition | community.general.json_query('interfaces_.ansible_facts.ansible_network_resources.interfaces[*].name') }}"

  - name: Interface
    pause:
      prompt: "[???] Which router interface would you like to set ? "
    register: ROUTER_INT

  - name: Enable {{ ROUTER_INT.user_input }} Interface on Router
    cisco.ios.ios_interfaces:
      config:
        - name: "{{ ROUTER_INT.user_input }}"
          description: Interface configured by Ansible
          enabled: true
