---
  - name: Enable {{ ROUTER_INT }} Interface on Router
    cisco.ios.ios_interfaces:
      config:
        - name: "{{ ROUTER_INT }}"
          description: Interface configured by Ansible
          enabled: true
