---
#------------------------------------------#INFORMATION#------------------------------------------#
  - name: INTERFACE | List of Interfaces
    debug:
      msg: "{{ interfaces_fact }}"    
#------------------------------------------#INFORMATION#------------------------------------------#

#------------------------------------------#INTERFACE#------------------------------------------#

#####CHOOSE-INTERFACE#####
  - name: INTERFACE | QUESTION 
    pause:
      prompt: "[???] Which router interface would you like to set ? (example : FastEthernet0/0)"
    register: ROUTER_INT
#####CHOOSE-INTERFACE#####
#####ADD-DESCRIPTION-TO-INTERFACE#####
  - name: INTERFACE | QUESTION
    pause:
      prompt: "[???] What description do you want to put on the interface ? "
    register: ROUTER_INT_DESC
#####ADD-DESCRIPTION-TO-INTERFACE#####

  - name: INTERFACE | Enable {{ ROUTER_INT.user_input }} Interface on Router
    cisco.ios.ios_interfaces:
      config:
        - name: "{{ ROUTER_INT.user_input }}"
          description: "{{ ROUTER_INT_DESC.user_input }}"
          enabled: true
#------------------------------------------#INTERFACE#------------------------------------------#

#------------------------------------------#RECAP#------------------------------------------#
  - name: INTERFACE | RECAP
    debug:
      msg: "You have choose the interface {{ ROUTER_INT.user_input }} to be enabled and you have add this in the description : {{ ROUTER_INT_DESC.user_input }}."
#------------------------------------------#RECAP#------------------------------------------#
