---
##################################LIST-OF-INTERFACES##################################

  - name: List of Interfaces
    debug:
      msg: "{{ interfaces_fact }}"
      
##################################LIST-OF-INTERFACES##################################

##################################CONFIG-OF-INTERFACES##################################

#####CHOOSE-INTERFACE#####
  - name: Interface
    pause:
      prompt: "[???] Which router interface would you like to set ? "
    register: ROUTER_INT
#####CHOOSE-INTERFACE#####
#####ADD-DESCRIPTION-TO-INTERFACE#####
  - name: Interface
    pause:
      prompt: "[???] What description do you want to put on the interface ? "
    register: ROUTER_INT_DESC
#####ADD-DESCRIPTION-TO-INTERFACE#####
#####APPLY-CONFIGURATION-TO-INTERFACE#####
  - name: Enable {{ ROUTER_INT.user_input }} Interface on Router
    cisco.ios.ios_interfaces:
      config:
        - name: "{{ ROUTER_INT.user_input }}"
          description: "{{ ROUTER_INT_DESC.user_input }}"
          enabled: true
#####APPLY-CONFIGURATION-TO-INTERFACE#####

#####RECAP-INTERFACE#####
  - name: RECAP
    debug:
      msg: "You have choose the interface {{ ROUTER_INT.user_input }} to be enabled and you have add this in the description : {{ ROUTER_INT_DESC.user_input }}."
#####RECAP-INTERFACE#####

##################################CONFIG-OF-INTERFACES##################################
