---
  - name: List of Interfaces
    debug:
      var: interfaces_

  - name: Interface
      pause:
        prompt: "[???] Which router interface would you like to set ? "
      register: ROUTER_INT

  - name: Enable {{ ROUTER_INT }} Interface on Router
    cisco.ios.ios_interfaces:
      config:
        - name: "{{ ROUTER_INT }}"
          description: Interface configured by Ansible
          enabled: true
