---
  - name: Enable and Add description to Interfaces on Routers
    cisco.ios.ios_interfaces:
      config:
        - name: "{{ ROUTER_INT }}"
          description: Interface configured by Ansible
          enabled: true
    ignore_errors: true
