---
######################################HOSTNAME######################################
  - name: Hostname Asking
    pause:
      prompt: "Which hostname would you like to set for you Router ? ( {{ inventory_hostname }} by default)
    register: HOSTNAME
      
  - name: Applying Hostname
    ios_config:
      lines: hostname {{ HOSTNAME }}
######################################HOSTNAME######################################

######################################DOMAIN######################################
  - name: Domain Asking
    pause:
      prompt: "Which domain would you like to set ? 
    register: DOMAIN

  - name: Configure Domain Name
    ios_system:
      domain_name: "{{ DOMAIN }}"
######################################DOMAIN######################################

######################################DNS-LOOKUP######################################
   - name: DNS_Lookup Asking
      pause:
        prompt: "Would you like to activate the DNS lookup ? (yes/no)
      register: DNS_LOOKUP
  
    - name: Configure DNS lookup sources
    ios_system:
      lookup_enabled: yes
    when: DNS_LOOKUP | bool
######################################DNS-LOOKUP######################################




  - include_tasks: interface_conf.yml
