---
#---------------------------------------------------------#EVERYONE-CONFIG#---------------------------------------------------------#
#------------------------------------------#BASICS#------------------------------------------#

  - name: BASICS
    pause:
      prompt: "[???] Would you like to customise the basic parameters ? (yes/no)"
    register: BASICS_CHOICE

  - include_tasks: basic_conf.yml
    when: BASICS_CHOICE.user_input | bool
    
#------------------------------------------#BASICS#------------------------------------------#

#------------------------------------------#INTERFACE#------------------------------------------#

  - name: INTERFACE
    pause:
      prompt: "[???] Would you like to customise an interface ? (yes/no)"
    register: INT_CHOICE

  - include_tasks: interface_conf.yml
    when: INT_CHOICE.user_input | bool
    
#------------------------------------------#INTERFACE#------------------------------------------#

#------------------------------------------#STATIC_ROUTE#------------------------------------------#

  - name: ROUTE
    pause:
      prompt: "[???] Would you like to customise a static route ? (yes/no)"
    register: ROUTE_CHOICE

  - include_tasks: ./Static_Route/main.yml
    when: ROUTE_CHOICE.user_input | bool
    
#------------------------------------------#STATIC_ROUTE#------------------------------------------#

#------------------------------------------#SECURITY#------------------------------------------#

  - name: SECURITY
    pause:
      prompt: "[???] Would you like to customise the security parameters ? (yes/no)"
    register: SECURITY_CHOICE

  - include_tasks: security_conf.yml
    when: SECURITY_CHOICE.user_input | bool
    
#------------------------------------------#SECURITY#------------------------------------------#

#------------------------------------------#SNMP#------------------------------------------#

  - name: SNMP
    pause:
      prompt: "[???] Would you like to customise the SNMP parameters ? (yes/no)"
    register: SNMP_CHOICE

  - include_tasks: snmp_conf.yml
    when: SNMP_CHOICE.user_input | bool
    
#------------------------------------------#SNMP#------------------------------------------#
#---------------------------------------------------------#EVERYONE-CONFIG#---------------------------------------------------------#

#---------------------------------------------------------#ROUTER-CONFIG#---------------------------------------------------------#
#------------------------------------------#ACLS#------------------------------------------#
  - include_tasks: ./ACLS/acls_main.yml
    when: (MACHINE_TYPE == "ROUTER") or (ansible_net_model == "2960") or (ansible_net_model == "3560") or (ansible_net_model == "3750") or (ansible_net_model == "3850")
#------------------------------------------#ACLS#------------------------------------------#
#---------------------------------------------------------#ROUTER-CONFIG#---------------------------------------------------------#

#---------------------------------------------------------#EVERYONE-CONFIG#---------------------------------------------------------#
#------------------------------------------#CONFIG-RECAP#------------------------------------------#
  - include_tasks: recap_config.yml
#------------------------------------------#CONFIG-RECAP#------------------------------------------#

#------------------------------------------#WRITE#------------------------------------------#
  - name: WRITE
    pause:
      prompt: "[???] Would you like to write the configuration ? (yes/no)"
    register: WRITE_CHOICE

  - include_tasks: write_conf.yml
    when: WRITE_CHOICE.user_input | bool
#------------------------------------------#WRITE#------------------------------------------#
#---------------------------------------------------------#EVERYONE-CONFIG#---------------------------------------------------------#
