---
######################################BASICS######################################

  - name: BASICS
    pause:
      prompt: "[???] Would you like to customise the basic parameters ? (yes/no)"
    register: BASICS_CHOICE

  - include_tasks: basic_conf.yml
    when: BASICS_CHOICE.user_input | bool
    
######################################BASICS######################################

######################################INTERFACE######################################

  - name: INTERFACE
    pause:
      prompt: "[???] Would you like to customise an interface ? (yes/no)"
    register: INT_CHOICE
    when: (MACHINE_TYPE == "ROUTER")

  - include_tasks: interface_conf.yml
    when: INT_CHOICE.user_input | bool
    
######################################INTERFACE######################################

######################################SECURITY######################################

  - name: SECURITY
    pause:
      prompt: "[???] Would you like to customise the security parameters ? (yes/no)"
    register: SECURITY_CHOICE

  - include_tasks: security_conf.yml
    when: SECURITY_CHOICE.user_input | bool
    
######################################SECURITY######################################

######################################SNMP######################################

  - name: SNMP
    pause:
      prompt: "[???] Would you like to customise the SNMP parameters ? (yes/no)"
    register: SNMP_CHOICE

  - include_tasks: snmp_conf.yml
    when: SNMP_CHOICE.user_input | bool
    
######################################SNMP######################################

######################################ACLS######################################

  - name: ACLS
    pause:
      prompt: "[???] Would you like to edit ACLS parameters ? (yes/no)"
    register: ACLS_CHOICE

  - include_tasks: ./ACLS/main.yml
    when: ACLS_CHOICE.user_input | bool
    
######################################ACLS######################################
