#------------------------------------#INFORMATION#------------------------------------#
  - name: INFORMATION
    debug:
       msg: "This role resume you all the change and action you have done !"
#------------------------------------#INFORMATION#------------------------------------#

#------------------------------------#RECAP-BASIC_CONF#------------------------------------#
  - name: RECAP (HOSTNAME)
    debug:
      msg: " You have set {{ HOSTNAME.user_input }} as Hostname."
    when: BASICS_CHOICE.user_input | bool

  - name: RECAP (DOMAIN)
    debug:
      msg: " You have set {{ DOMAIN.user_input }} as Domain."
    when: BASICS_CHOICE.user_input | bool

  - name: RECAP (BASE-BANNER)
    debug:
      msg: " You have add {{ BASE_BANNER.user_input }} as Base Banner."
    when: (BASICS_CHOICE.user_input == "yes") and (BASE_BANNER_CHOICE.user_input == "yes")

  - name: RECAP (LOGIN-BANNER)
    debug:
      msg: " You have add {{ LOGIN_BANNER.user_input }} as Login Banner."
    when: (BASICS_CHOICE.user_input == "yes") and (LOGIN_BANNER_CHOICE.user_input == "yes")
#------------------------------------#RECAP-BASIC_CONF#------------------------------------#

#------------------------------------#RECAP-INTERFACE#------------------------------------#
  - name: RECAP (INTERFACE)
    debug:
      msg: "You have choose the interface {{ ROUTER_INT.user_input }} to be enabled and you have add this in the description : {{ ROUTER_INT_DESC.user_input }}."
    when: INT_CHOICE.user_input | bool
#------------------------------------#RECAP-INTERFACE#------------------------------------#

#------------------------------------#RECAP-SECURITY#------------------------------------#
  - name: RECAP (SECURITY)
    debug:
      msg: " You have decided to create a new User named : {{ CISCO_USER.user_input }} with a level of privilege of : {{ CISCO_USER_PRIVILEGE.user_input }}."
    when: (CISCO_USER_CHOICE.user_input == "yes") and (SECURITY_CHOICE.user_input == "yes")
#------------------------------------#RECAP-SECURITY#------------------------------------#

#------------------------------------#RECAP-SNMP#------------------------------------#
  - name: RECAP (SNMP)
    debug:
      msg: " You have decided to set up a PUBLIC SNMP Server : {{ SNMP_PUBLIC.user_input }} ."
    when: (SNMP_PUBLIC_CHOICE.user_input == "yes") and (SNMP_CHOICE.user_input == "yes")

  - name: RECAP (SNMP)
    debug:
      msg: " You have decided to set up a PRIVATE SNMP Server : {{ SNMP_PRIVATE.user_input }} ."
    when: (SNMP_PRIVATE_CHOICE.user_input == "yes") and (SNMP_CHOICE.user_input == "yes")
#------------------------------------#RECAP-SNMP#------------------------------------#

#------------------------------------#RECAP-ACLS_DESTRUCTOR#------------------------------------#
  - name: RECAP (ACLS_DESTRUCTOR)
    debug:
      msg: " You have decided to delete all ACLS already present ."
    when: (ACLS_DELETE_ALL.user_input == "yes") and (ACLS_CHOICE.user_input == "yes") and (ACLS_DESTRUCTOR_CHOICE.user_input == "yes")

  - name: RECAP (ACLS_DESTRUCTOR)
    debug:
      msg: " You have decided to delete all ACLS based on AFI {{ ACLS_DELETE_AFI_BASED_TYPE.user_input }} already present ."
    when: (ACLS_DELETE_ALL.user_input == "no") and (ACLS_CHOICE.user_input == "yes") and (ACLS_DESTRUCTOR_CHOICE.user_input == "yes")
#------------------------------------#RECAP-ACLS_DESTRUCTOR#------------------------------------#

#------------------------------------#RECAP-ACLS_CREATOR#------------------------------------#
  - name: RECAP (Gather ACLS current configuration)
    cisco.ios.ios_acls:
      state: gathered
    register: ACLS_current

  - name: RECAP (List current ACLS)
    debug:
      var: ACLS
#------------------------------------#RECAP-ACLS_CREATOR#------------------------------------#

#------------------------------------#RECAP-EASTER_EGG#------------------------------------#
⠀
#------------------------------------#RECAP-EASTER_EGG#------------------------------------#
