#------------------------------------------#INFORMATION#------------------------------------------#
  - name: INFORMATION
    debug:
       msg: "This role resume you all the change and action you have done !"
#------------------------------------------#INFORMATION#------------------------------------------#

#------------------------------------------#RECAP-BASICS#------------------------------------------#
  - name: RECAP | HOSTNAME
    debug:
      msg: " You have set {{ HOSTNAME.user_input }} as Hostname."
    when: BASICS_CHOICE.user_input | bool

  - name: RECAP | DOMAIN
    debug:
      msg: " You have set {{ DOMAIN.user_input }} as Domain."
    when: BASICS_CHOICE.user_input | bool

  - name: RECAP | BASE-BANNER
    debug:
      msg: " You have add {{ BASE_BANNER.user_input }} as Base Banner."
    when: (BASICS_CHOICE.user_input == "yes") and (BASE_BANNER_CHOICE.user_input == "yes")

  - name: RECAP | LOGIN-BANNER
    debug:
      msg: " You have add {{ LOGIN_BANNER.user_input }} as Login Banner."
    when: (BASICS_CHOICE.user_input == "yes") and (LOGIN_BANNER_CHOICE.user_input == "yes")
#------------------------------------------#RECAP-BASICS#------------------------------------------#

#------------------------------------------#RECAP-INTERFACE#------------------------------------------#
  - name: RECAP | INTERFACE
    debug:
      msg: "You have choose the interface {{ ROUTER_INT.user_input }} to be enabled and you have add this in the description : {{ ROUTER_INT_DESC.user_input }}."
    when: INT_CHOICE.user_input | bool
#------------------------------------------#RECAP-INTERFACE#------------------------------------------#

#------------------------------------------#RECAP-SECURITY#------------------------------------------#
#  - name: RECAP (SECURITY)
#    debug:
#      msg: " You have decided to create a new User named : {{ CISCO_USER.user_input }} with a level of privilege of : {{ CISCO_USER_PRIVILEGE.user_input }}."
#    when: (CISCO_USER_CHOICE.user_input == "yes") and (SECURITY_CHOICE.user_input == "yes")

  - name: RECAP | SECURITY
    block:
        - name: RECAP | SECURITY
          debug:
            msg: " You have decided to create a new User named : {{ CISCO_USER.user_input }} with a level of privilege of : {{ CISCO_USER_PRIVILEGE.user_input }}."
          when: (CISCO_USER_CHOICE.user_input == "yes")
    when: (SECURITY_CHOICE.user_input == "yes")

  - name: RECAP | SCP
    debug:
      msg: " You said {{ SCP_SERVER_CHOICE.user_input }} to activating the scp server."
    when: (SECURITY_CHOICE.user_input == "yes")
#------------------------------------------#RECAP-SECURITY#------------------------------------------#

#------------------------------------------#RECAP-SNMP#------------------------------------------#
#  - name: RECAP (SNMP)
#    debug:
#      msg: " You have decided to set up a PUBLIC SNMP Server : {{ SNMP_PUBLIC.user_input }} ."
#    when: (SNMP_PUBLIC_CHOICE.user_input == "yes") and (SNMP_CHOICE.user_input == "yes")
#
#  - name: RECAP (SNMP)
#    debug:
#      msg: " You have decided to set up a PRIVATE SNMP Server : {{ SNMP_PRIVATE.user_input }} ."
#    when: (SNMP_PRIVATE_CHOICE.user_input == "yes") and (SNMP_CHOICE.user_input == "yes")

  - name: RECAP | SNMP
    block:
        - name: RECAP | SNMP - Public Server
          debug:
            msg: " You have decided to set up a PUBLIC SNMP Server : {{ SNMP_PUBLIC.user_input }} ."
          when: (SNMP_PUBLIC_CHOICE.user_input == "yes")

        - name: RECAP | SNMP - Private Server
          debug:
            msg: " You have decided to set up a PRIVATE SNMP Server : {{ SNMP_PRIVATE.user_input }} ."
          when: (SNMP_PRIVATE_CHOICE.user_input == "yes")
    when: (SNMP_CHOICE.user_input == "yes")
#------------------------------------------#RECAP-SNMP#------------------------------------------#

#------------------------------------------#RECAP-ACLS_DESTRUCTOR#------------------------------------------#
#  - name: RECAP (ACLS_DESTRUCTOR)
#    debug:
#      msg: " You have decided to delete all ACLS already present ."
#    when: (ACLS_DELETE_ALL.user_input == "yes") and (ACLS_CHOICE.user_input == "yes") and (ACLS_DESTRUCTOR_CHOICE.user_input == "yes")
#
#  - name: RECAP (ACLS_DESTRUCTOR)
#    debug:
#      msg: " You have decided to delete all ACLS based on AFI {{ ACLS_DELETE_AFI_BASED_TYPE.user_input }} already present ."
#    when: (ACLS_DELETE_ALL.user_input == "no") and (ACLS_CHOICE.user_input == "yes") and (ACLS_DESTRUCTOR_CHOICE.user_input == "yes")

  - name: RECAP | ACLS_DESTRUCTOR
    block:
        - name: RECAP | ACLS_DESTRUCTOR
          debug:
            msg: " You have decided to delete all ACLS already present ."
          when: (ACLS_DELETE_ALL.user_input == "yes") and (ACLS_DESTRUCTOR_CHOICE.user_input == "yes")
  
        - name: RECAP | ACLS_DESTRUCTOR
          debug:
            msg: " You have decided to delete all ACLS based on AFI {{ ACLS_DELETE_AFI_BASED_TYPE.user_input }} already present ."
          when: (ACLS_DELETE_ALL.user_input == "no") and (ACLS_DESTRUCTOR_CHOICE.user_input == "yes")
    when: (ACLS_CHOICE.user_input == "yes")
#------------------------------------------#RECAP-ACLS_DESTRUCTOR#------------------------------------------#

#------------------------------------------#RECAP-ACLS_CREATOR#------------------------------------------#
  - name: RECAP | ACLS - Gather ACLS configuration
    cisco.ios.ios_acls:
      state: gathered
    register: ACLS_current

  - name: RECAP | ACLS - Show ACLS configuration
    debug:
      var: ACLS_current
#------------------------------------------#RECAP-ACLS_CREATOR#------------------------------------------#

#------------------------------------------#RECAP-ACLS_DESTRUCTOR#------------------------------------------#
  - name: RECAP | ROUTE_DESTRUCTOR
    block:
        - name: RECAP | ROUTE_DESTRUCTOR
          debug:
            msg: " You have decided to delete all Static Route already present ."
          when: (ROUTE_DELETE_ALL.user_input == "yes") and (ROUTE_DESTRUCTOR_CHOICE.user_input == "yes")
  
#        - name: RECAP | ROUTE_DESTRUCTOR
#          debug:
#            msg: " You have decided to delete all Static Route based on VRF {{ ROUTE_DELETE_VRF_BASED_TYPE.user_input }} already present ."
#          when: (ROUTE_DELETE_ALL.user_input == "no") and (ROUTE_DESTRUCTOR_CHOICE.user_input == "yes")
    when: (ROUTE_CHOICE.user_input == "yes")
#------------------------------------------#RECAP-ACLS_DESTRUCTOR#------------------------------------------#

#------------------------------------------#RECAP-ACLS_CREATOR#------------------------------------------#
  - name: ROUTE | Gather Static Route configuration 
    cisco.ios.ios_static_routes:
      config:
      state: gathered
    register: ROUTE_current

  - name: ROUTE | List Static Route
    debug:
      var: ROUTE_current
#------------------------------------------#RECAP-ACLS_CREATOR#------------------------------------------#
