#########################SNMP-CONFIGURATION#########################

#####PROMPT#####
  - name: SNMP
    pause:
      prompt: "[???] Would you like to set up a Public SNMP server ? (yes/no)"
    register: SNMP_PUBLIC_CHOICE

  - name: SNMP
    pause:
      prompt: "[???] Would you like to set up a Private SNMP server ? (yes/no)"
    register: SNMP_PRIVATE_CHOICE

  - name: SNMP
    pause:
      prompt: "[???] What PUBLIC SNMP server whould you like to set ? "
    register: SNMP_PUBLIC
    when: SNMP_PUBLIC_CHOICE.user_input | bool

  - name: SNMP
    pause:
      prompt: "[???] What PRIVATE SNMP server whould you like to set ? "
    register: SNMP_PRIVATE
    when: SNMP_PRIVATE_CHOICE.user_input | bool
#####PROMPT#####

#####APPLY-CONFIG#####
  - name: "Configuration of the SNMP Public Server ( {{ SNMP_PUBLIC.user_input }} )"
    ios_config:
      commands:
        - snmp-server community {{ SNMP_PUBLIC.user_input }} RO
    when: SNMP_PUBLIC_CHOICE.user_input | bool

  - name: "Configuration of the SNMP private Server ( {{ SNMP_PRIVATE.user_input }} )"
    ios_config:
      commands:
        - snmp-server community {{ SNMP_PRIVATE.user_input }} RW
    when: SNMP_PRIVATE_CHOICE.user_input | bool
#####APPLY-CONFIG#####

#####RECAP#####

#####RECAP#####

#########################SNMP-CONFIGURATION#########################
