#------------------------------------#INFORMATION#------------------------------------#
  - name: INFORMATION
    debug:
       msg: "Starting writing the configuration..."
#------------------------------------#INFORMATION#------------------------------------#

  - name: WRITING CONFIGURATION
    ios_config:
      commands:
        - write
