#------------------------------------------#INFORMATION#------------------------------------------#
  - name: INFORMATION
    debug:
       msg: "Starting writing the configuration..."
#------------------------------------------#INFORMATION#------------------------------------------#

#------------------------------------------#WRITE#------------------------------------------#
  - name: ✍️ WRITE | Writing configuration
    cisco.ios.ios_command:
      commands: write
    register: writing_result

  - name: ✍️ WRITE | Showing the result of writing configuration
    debug:
      var: writing_result
#------------------------------------------#WRITE#------------------------------------------#

#------------------------------------#RECAP#------------------------------------#
  - name: ✍️ WRITE | Gather Configuration
    cisco.ios.ios_command:
      commands: show run
    register: showrun_result

  - name: ✍️ WRITE | Show Running configuration
    debug:
      var: showrun_result
#------------------------------------#RECAP#------------------------------------#
