#------------------------------------#INFORMATION#------------------------------------#
  - name: INFORMATION
    debug:
       msg: "Starting writing the configuration..."
#------------------------------------#INFORMATION#------------------------------------#

#------------------------------------#ACTION#------------------------------------#
  - name: WRITING CONFIGURATION
    ios_config:
      commands:
        - write
    register: writing_result
#------------------------------------#ACTION#------------------------------------#

#------------------------------------#RESULT#------------------------------------#
  - name: RESULT
    debug:
      var: writing_result
#------------------------------------#RESULT#------------------------------------#
