#------------------------------------#INFORMATION#------------------------------------#
  - name: INFORMATION
    debug:
       msg: "Starting writing the configuration..."
#------------------------------------#INFORMATION#------------------------------------#
