#------------------------------------#INFORMATION#------------------------------------#
  - name: INFORMATION
    debug:
       msg: "Starting writing the configuration..."
#------------------------------------#INFORMATION#------------------------------------#

#------------------------------------#ACTION#------------------------------------#
  - name: WRITING CONFIGURATION
    cisco.ios.ios_command:
      commands: write
    register: writing_result
#------------------------------------#ACTION#------------------------------------#

#------------------------------------#RESULT[ACTION]#------------------------------------#
  - name: RESULT
    debug:
      var: writing_result
#------------------------------------#RESULT[ACTION]#------------------------------------#

#------------------------------------#RESULT[CONF]#------------------------------------#
  - name: Gather Configuration
    cisco.ios.ios_command:
      commands: show run
    register: showrun_result

  - name: Show Running configuration
    debug:
      var: showrun_result
#------------------------------------#RESULT[CONF]#------------------------------------#
