- name: Display existing Docker containers
  debug:
    var: docker_containers.stdout_lines

- name: CONTAINER - REMOVE
  pause:
    prompt: "[???] Which container would you like to remove (name) ? "
  register: container_rm_name


- name: Remove container
  community.docker.docker_container:
    name: "{{ container_rm_name.user_input }}"
    state: absent

- name: Update existing Docker containers
  command: docker ps -a
  register: docker_containers
