#-----------------------------#CHECK-CONTAINERS#-----------------------------#
- name: Check existing Docker containers
  command: docker ps -a
  register: docker_containers
#-----------------------------#CHECK-CONTAINERS#-----------------------------#

#-----------------------------#CHECK-IMAGES#-----------------------------#
- name: Check existing Docker images
  command: docker images
  register: docker_images
#-----------------------------#CHECK-IMAGES#-----------------------------#
