--- 
  - name: Include the variables
    ansible.builtin.include_vars: /etc/ansible/roles/Learning-Ansible/Cisco_Switch/VARS.yml

  - name: Configuration of SNMP public and private
    ios_config:
      commands:
        - snmp-server community {{ SNMP_PUBLIC }} RO
        - snmp-server community {{ SNMP_PRIVATE }} RW
        - snmp-server community {{ SNMP_PRIVATE_TEST }} RW
#        - snmp-server community ansible-cisco-public RO
#        - snmp-server community ansible-cisco-private RW
#        - snmp-server community ansible-cisco-private-test RW
