#-----------------------------#REBOOT#-----------------------------#
    - name: UPDATES
      pause:
        prompt: "[???] Choose a type of reboot ? (classic/update/slow)"
      register: REBOOT_CHOICE
#-----------------------------#REBOOT#-----------------------------#

- name: Reboot Classic
  ansible.windows.win_reboot:

- name: Reboot for Update
  ansible.windows.win_reboot:
    reboot_timeout: 3600

- name: Reboot Slow
  ansible.windows.win_reboot:
    post_reboot_delay: 120
