#-----------------------------#REBOOT-INFORMATION#-----------------------------#
    - name: INFORMATION - Classic Reboot
      debug:
          msg: "Classic Reboot : Reboot the machine with all defaults."

    - name: INFORMATION - Update Reboot
      debug:
          msg: "Update Reboot : Reboot a slow machine that might have lots of updates to apply."

    - name: INFORMATION - Slow Reboot
      debug:
          msg: "Slow Reboot : Reboot a machine that takes time to settle after being booted."
#-----------------------------#REBOOT-INFORMATION#-----------------------------#

#-----------------------------#REBOOT-ASK#-----------------------------#
    - name: UPDATES
      pause:
        prompt: "[???] Choose a type of reboot ? (classic/update/slow)"
      register: REBOOT_CHOICE
#-----------------------------#REBOOT-ASK#-----------------------------#

#-----------------------------#REBOOT#-----------------------------#
    - name: Reboot Classic
      ansible.windows.win_reboot:
      when: REBOOT_CHOICE is defined and REBOOT_CHOICE.user_input in ["classic"]    
    
    - name: Reboot for Update
      ansible.windows.win_reboot:
        reboot_timeout: 3600
      when: REBOOT_CHOICE is defined and REBOOT_CHOICE.user_input in ["update"]    
    
    - name: Reboot Slow
      ansible.windows.win_reboot:
        post_reboot_delay: 120
      when: REBOOT_CHOICE is defined and REBOOT_CHOICE.user_input in ["slow"]    
#-----------------------------#REBOOT#-----------------------------#
