---
  - name: Configure the Users
    ios_config:
      lines:
      - username scp privilege 15 password {{ CISCO_SCP_PASS }}

  - name: Enable scp server
    ios_config:
      lines: ip scp server enable 

  - name: Copy running config
    command:  
