- name: Display existing Docker images
  debug:
    var: docker_images.stdout_lines

- name: IMAGES - INSPECT
  pause:
    prompt: "[???] Which image do you want to inspect ?"
  register: IMAGES_INSPECT_NAME

- name: Inspect "{{ IMAGES_INSPECT_NAME.user_input }}"
  community.docker.docker_image_info:
    name: "{{ IMAGES_INSPECT_NAME.user_input }}"
  register: IMAGES_INSPECT_RESULT

- name: Display inspection result
  debug:
    var: IMAGES_INSPECT_RESULT.images
