- name: IMAGES
  pause:
    prompt: "[???] Do you want to inspect an image ? (yes/no)"
  register: IMAGES_INSPECT_CHOICE

- include_tasks: inspect_images.yml
  when: IMAGES_INSPECT_CHOICE.user_input | bool

- name: IMAGES
  pause:
    prompt: "[???] Do you want to pull an image ? (yes/no)"
  register: IMAGES_PULL_CHOICE

- include_tasks: pull_images.yml
  when: IMAGES_PULL_CHOICE.user_input | bool

- name: IMAGES
  pause:
    prompt: "[???] Do you want to remove an image ? (yes/no)"
  register: IMAGES_REMOVE_CHOICE

- include_tasks: remove_images.yml
  when: IMAGES_REMOVE_CHOICE.user_input | bool
