- name: IMAGES - PULL
  pause:
    prompt: "[???] Which image do you want to pull ?"
  register: IMAGES_PULL_NAME

- name: Pull an image
  community.docker.docker_image:
    name: "{{ IMAGES_PULL_NAME.user_input }}"
    source: pull
    # Select platform for pulling. If not specified, will pull whatever docker prefers.
#    platform: amd64

- name: Inspect "{{ IMAGES_PULL_NAME.user_input }}"
  community.docker.docker_image_info:
    name: "{{ IMAGES_PULL_NAME.user_input }}"
  register: IMAGES_PULL_INSPECT_RESULT

- name: Display inspection result
  debug:
    var: IMAGES_PULL_INSPECT_RESULT.images

- name: IMAGES
  pause:
    prompt: "[???] Do you want to pull another image ? (yes/no)"
  register: IMAGES_PULL_REASK_CHOICE

- include_tasks: pull_images.yml
  when: IMAGES_PULL_REASK_CHOICE.user_input | bool

- name: Update existing Docker images
  command: docker images
  register: docker_images
