- name: IMAGES - PULL
  pause:
    prompt: "[???] Which image do you want to pull ?"
  register: IMAGES_PULL_NAME

- name: Pull an image
  community.docker.docker_image:
    name: "{{ IMAGES_PULL_NAME.user_input }}"
    source: pull
    # Select platform for pulling. If not specified, will pull whatever docker prefers.
#    platform: amd64

- name: Inspect "{{ IMAGES_PULL_NAME.user_input }}"
  community.docker.docker_image_info:
    name: "{{ IMAGES_PULL_NAME.user_input }}"
