- name: IMAGES
  pause:
    prompt: "[???] Which image do you want to pull ?"
  register: IMAGES_PULL_NAME

- name: Pull an image
  community.docker.docker_image_pull:
    name: "{{ IMAGES_PULL_NAME.user_input }}"
    # Select platform for pulling. If not specified, will pull whatever docker prefers.
#    platform: amd64
