                                                            #      #####    #       #####
                                                           # #     #        #       #
                                                          #   #    #        #       ##### 
                                                          #####    #        #           # 
                                                          #   #    #####    ####    #####


####################################################################PROMPT####################################################################

#####ACLS_NAME#####
  - name: ACLS
    pause:
      prompt: "[???] What name do you want to set ?"
    register: ACLS_NAME
#####ACLS_NAME#####

