                                                            #      #####    #       #####
                                                           # #     #        #       #
                                                          #   #    #        #       ##### 
                                                          #####    #        #           # 
                                                          #   #    #####    ####    #####


####################################################################PROMPT####################################################################

#####ACLS_COMMAND_LINE#####
  - name: ACLS
    pause:
      prompt: "[???] Write your ACLs command here : (example : "
    register: ACLS_COMMAND_LINE
#####ACLS_COMMAND_LINE#####

#####ACLS_LINE_CREATOR#####
  - name: Apply the ACLs configuration
    cisco.ios.ios_command:
      commands: {{ ACLS_COMMAND_LINE.user_input }}
#####ACLS_LINE_CREATOR#####
