##################################CONFIG-OF-ACLS##################################

#####CHOOSE-INTERFACE#####
  - name: Interface
    pause:
      prompt: "[???] Which router interface would you like to set ? "
    register: ROUTER_INT
#####CHOOSE-INTERFACE#####
#####ADD-DESCRIPTION-TO-INTERFACE#####
  - name: Interface
    pause:
      prompt: "[???] What description do you want to put on the interface ? "
    register: ROUTER_INT_DESC
#####ADD-DESCRIPTION-TO-INTERFACE#####

#####APPLY-CONFIGURATION#####
  - name: Replaces device configuration of listed acls with provided configuration
  cisco.ios.ios_acls:
    config:
      - afi: ipv4
        acls:
          - name: 110
            aces:
              - grant: deny
                protocol_options:
                  tcp:
                    syn: true
                source:
                  address: 192.0.2.0
                  wildcard_bits: 0.0.0.255
                destination:
                  address: 192.0.3.0
                  wildcard_bits: 0.0.0.255
                  port_protocol:
                    eq: www
                dscp: ef
                ttl:
                  eq: 10
          - name: 150
            aces:
              - grant: deny
                sequence: 20
                protocol_options:
                  tcp:
                    syn: true
                source:
                  address: 198.51.100.0
                  wildcard_bits: 0.0.0.255
                  port_protocol:
                    eq: telnet
                destination:
                  address: 198.51.110.0
                  wildcard_bits: 0.0.0.255
                  port_protocol:
                    eq: telnet
                dscp: ef
                ttl:
                  eq: 10
    state: replaced
#####APPLY-CONFIGURATION#####
