####################################################################PROMPT####################################################################
  - name: ACLS
    pause:
      prompt: "[???] Do you want to delete ALL of configured ACLs ? (yes/no)"
    register: ACLS_DELETE_ALL

  - name: ACLS
    pause:
      prompt: "[???] Do you want to delete ACLs based on AFI ? (yes/no)"
    register: ACLS_DELETE_AFI_BASED
    when: ACLS_DELETE_ALL.user_input == "no"
####################################################################PROMPT####################################################################

####################################################################SCRIPT####################################################################
- name: Delete ALL of configured ACLs
  cisco.ios.ios_acls:
    state: deleted

- name: "Delete ACLs based on AFI (Note: This won't delete the all configured ACLs)"
  cisco.ios.ios_acls:
    config:
      - afi: ipv4
    state: deleted
####################################################################SCRIPT####################################################################
