####################################################################PROMPT####################################################################

#####ACLS-STATE#####
  - name: ACLS
    pause:
      prompt: "[???] Which STATE you want your ACLs to be ? [merged/replaced/overriden/deleted/rendered]"
    register: ACLS_STATE
#####ACLS-STATE#####

#####ACLS-AFI#####
  - name: ACLS
    pause:
      prompt: "[???] Which type of AFI you want your ACLs to be ? [ipv4/ipv6]"
    register: ACLS_AFI
#####ACLS-AFI#####

#####ACLS-GRANT#####
  - name: ACLS
    pause:
      prompt: "[???] Which type of GRANT you want your ACLs to be ? [permit/deny]"
    register: ACLS_GRANT
#####ACLS-GRANT#####

####################################################################PROMPT####################################################################

####################################################################CONFIG-OF-ACLS####################################################################

#####APPLY-CONFIGURATION#####
  - name: Apply the new ACLs configuration
    cisco.ios.ios_acls:
      config:
        - afi: {{ ACLS_AFI.user_input }}
          acls:
            - name: 110
              aces:
                - grant: {{ ACLS_GRANT.user_input }}
                  protocol_options:
                    tcp:
                      syn: true
                  source:
                    address: 192.0.2.0
                    wildcard_bits: 0.0.0.255
                  destination:
                    address: 192.0.3.0
                    wildcard_bits: 0.0.0.255
                    port_protocol:
                      eq: www
                  dscp: ef
                  ttl:
                    eq: 10
#            - name: 150
#              aces:
#                - grant: deny
#                  sequence: 20
#                  protocol_options:
#                    tcp:
#                      syn: true
#                  source:
#                    address: 198.51.100.0
#                    wildcard_bits: 0.0.0.255
#                    port_protocol:
#                      eq: telnet
#                  destination:
#                    address: 198.51.110.0
#                    wildcard_bits: 0.0.0.255
#                    port_protocol:
#                      eq: telnet
#                  dscp: ef
#                  ttl:
#                    eq: 10
      state: {{ ACLS_STATE.user_ }}
#####APPLY-CONFIGURATION#####
####################################################################CONFIG-OF-ACLS####################################################################
