                                                            #      #####    #       #####
                                                           # #     #        #       #
                                                          #   #    #        #       ##### 
                                                          #####    #        #           # 
                                                          #   #    #####    ####    #####


####################################################################PROMPT####################################################################
#####ACLS_LINE_NAME#####
  - name: ACLS
    pause:
      prompt: "[???] What name would you like for your ACLs ? "
    register: ACLS_LINE_NAME
#####ACLS_LINE_NAME#####

#####ACLS_LINE_TYPE#####
  - name: ACLS
    pause:
      prompt: "[???] What type would you like your ACLs to be ? (extended/standard/resequence/logging/log-update)"
    register: ACLS_LINE_TYPE
#####ACLS_LINE_TYPE#####

#####ACLS_COMMAND_LINE#####
#  - name: ACLS
#    pause:
#      prompt: "[???] Write your ACLs command here : (example : deny icmp 192.0.2.0 0.0.0.255 192.0.3.0 0.0.0.255 echo dscp ef ttl eq 10"
#    register: ACLS_COMMAND_LINE
#####ACLS_COMMAND_LINE#####

#####ACLS-GRANT#####
  - name: ACLS
    pause:
      prompt: "[???] Which type of GRANT you want your ACLs to be ? [permit/deny]"
    register: ACLS_GRANT
#####ACLS-GRANT#####

#########################################################################################################################################################
#####ACLS-SOURCE#####
  - name: ACLS
    pause:
      prompt: "[???] SOURCE IP ? "
    register: ACLS_SOURCE_IP

  - name: ACLS
    pause:
      prompt: "[???] SOURCE Wildcard_bits ? "
    register: ACLS_SOURCE_WILD
#####ACLS-SOURCE#####
#####ACLS-DESTINATION#####
  - name: ACLS
    pause:
      prompt: "[???] DESTINATION IP ? "
    register: ACLS_DEST_IP

  - name: ACLS
    pause:
      prompt: "[???] DESTINATION Wildcard_bits ? "
    register: ACLS_DEST_WILD
#####ACLS-DESTINATION#####
####################################################################PROMPT####################################################################

####################################################################SCRIPT####################################################################
#####ACLS_LINE_CREATOR#####
  - name: Apply the ACLs configuration
    cisco.ios.ios_config:
      lines:
        - "ip access-list {{ ACLS_LINE_TYPE.user_input }} {{ ACLS_LINE_NAME.user_input }}"
        - "{{ ACLS_GRANT.user_input }} {{ ACLS_GRANT.user_input }}"
#####ACLS_LINE_CREATOR#####
####################################################################SCRIPT####################################################################

####################################################################OTHER####################################################################
#####INFORMATION#####
  - name: INFORMATION
    debug:
      msg: "Done ! Your ACLs configuration has been deployed perfectly !"
#####INFORMATION#####
####################################################################OTHER####################################################################
