                                                            #      #####    #       #####
                                                           # #     #        #       #
                                                          #   #    #        #       ##### 
                                                          #####    #        #           # 
                                                          #   #    #####    ####    #####


####################################################################PROMPT####################################################################
####################################################################COMMAND-1####################################################################
#####ACLS_LINE_NAME#####
  - name: ACLS
    pause:
      prompt: "[???] What name would you like for your ACLs ? "
    register: ACLS_LINE_NAME
#####ACLS_LINE_NAME#####

#####ACLS_LINE_TYPE#####
  - name: ACLS
    pause:
      prompt: "[???] What type would you like your ACLs to be ? (extended/standard/resequence/logging/log-update)"
    register: ACLS_LINE_TYPE
#####ACLS_LINE_TYPE#####
####################################################################COMMAND-1####################################################################

####################################################################COMMAND-2####################################################################
#####ACLS-GRANT#####
  - name: ACLS
    pause:
      prompt: "[???] Which type of GRANT you want your ACLs to be ? (permit/deny)"
    register: ACLS_GRANT
#####ACLS-GRANT#####

#####ACLS-PROTOCOL#####
  - name: ACLS
    pause:
      prompt: "[???] Which protocol should the rule apply to? (ahp/eigrp/esp/gre/icmp/igmp/ip/ipinip/nos/ospf/pcp/pim/tcp/udp)"
    register: ACLS_BASE_PROTOCOL
#####ACLS-PROTOCOL#####

#####ACLS-SOURCE#####
  - name: ACLS
    pause:
      prompt: "[???] Configure your SOURCE host : (any/host/[ip])"
    register: ACLS_SOURCE_IP
#####ACLS-SOURCE#####
#####ACLS-DESTINATION#####
  - name: ACLS
    pause:
      prompt: "[???] Configure your DESTINATION host : (any/host/[ip])"
    register: ACLS_DEST_IP
#####ACLS-DESTINATION#####

###################################ACLS-1-PARAMETERS###################################
#####HELP#####
  - name: ACLS
    pause:
      prompt: "[???] Would you like a list of all option and parameters you can add ? (yes/no)"
    register: ACLS_OPTION_LIST_CHOICE

  - name: ACLS
    ansible.builtin.debug:
      msg: |
      "{{ lookup('ansible.builtin.file', './HELP_DOC/ACLS_OPTIONSPARAMETERS.txt') }}"
    when: ACLS_OPTION_LIST_CHOICE.user_input | bool

#####HELP#####

  - name: ACLS
    pause:
      prompt: "[???] Which options would you like to add ? (format : ttl eq 10 )"
    register: ACLS_OPTION
###################################ACLS-1-PARAMETERS###################################
####################################################################COMMAND-2####################################################################
####################################################################PROMPT####################################################################

####################################################################VALIDATION####################################################################
  - name: "Your Access-List :"
    debug:
      msg: "{{ ACLS_GRANT.user_input }} {{ ACLS_BASE_PROTOCOL.user_input }} {{ ACLS_SOURCE_IP.user_input }} {{ ACLS_DEST_IP.user_input }} {{ ACLS_OPTION.user_input }}"

  - name: ACLS
    pause:
      prompt: "[???] Are you sure you want to apply this Access-List ? (yes/no)"
    register: ACLS_VALIDATION_CHOICE
####################################################################VALIDATION####################################################################

####################################################################SCRIPT####################################################################
#####ACLS_LINE_CREATOR#####
  - name: Apply the ACLs configuration
    cisco.ios.ios_config:
      lines:
        - "ip access-list {{ ACLS_LINE_TYPE.user_input }} {{ ACLS_LINE_NAME.user_input }}"
        - "{{ ACLS_GRANT.user_input }} {{ ACLS_BASE_PROTOCOL.user_input }} {{ ACLS_SOURCE_IP.user_input }} {{ ACLS_DEST_IP.user_input }} {{ ACLS_OPTION.user_input }}"
    when: ACLS_VALIDATION_CHOICE.user_input | bool
#####ACLS_LINE_CREATOR#####
####################################################################SCRIPT####################################################################

####################################################################OTHER####################################################################
#####INFORMATION#####
  - name: INFORMATION
    debug:
      msg: "Done ! Your ACLs configuration has been deployed perfectly !"
    when: ACLS_VALIDATION_CHOICE.user_input | bool

  - name: INFORMATION
    debug:
      msg: "Configuration aborted !"
    when: ACLS_VALIDATION_CHOICE.user_input == "no"
#####INFORMATION#####

#####RECAP#####
  - name: "RECAP of {{ ACLS_LINE_NAME.user_input }}"
    debug:
      msg: "{{ ACLS_GRANT.user_input }} {{ ACLS_BASE_PROTOCOL.user_input }} {{ ACLS_SOURCE_IP.user_input }} {{ ACLS_DEST_IP.user_input }} {{ ACLS_OPTION.user_input }}"
    when: ACLS_VALIDATION_CHOICE.user_input | bool
#####RECAP#####
####################################################################OTHER####################################################################
