                                                            #      #####    #       #####
                                                           # #     #        #       #
                                                          #   #    #        #       ##### 
                                                          #####    #        #           # 
                                                          #   #    #####    ####    #####


####################################################################PROMPT####################################################################
#####ACLS_LINE_NAME#####
  - name: ACLS
    pause:
      prompt: "[???] What name would you like for your ACLs ? "
    register: ACLS_LINE_NAME
#####ACLS_LINE_NAME#####

#####ACLS_LINE_TYPE#####
  - name: ACLS
    pause:
      prompt: "[???] What type would you like your ACLs to be ? (extended/standard/resequence/logging/log-update)"
    register: ACLS_LINE_TYPE
#####ACLS_LINE_TYPE#####

#####ACLS_COMMAND_LINE#####
  - name: ACLS
    pause:
      prompt: "[???] Write your ACLs command here : "
    register: ACLS_COMMAND_LINE
#####ACLS_COMMAND_LINE#####

#####ACLS_LINE_CREATOR#####
  - name: Apply the ACLs configuration
    cisco.ios.ios_config:
      lines:
        - ip access-list {{ ACLS_LINE_TYPE.user_input }} {{ ACLS_LINE_NAME.user_input }}
        - {{ ACLS_COMMAND_LINE.user_input }}
#####ACLS_LINE_CREATOR#####
