                                                            #      #####    #       #####
                                                           # #     #        #       #
                                                          #   #    #        #       ##### 
                                                          #####    #        #           # 
                                                          #   #    #####    ####    #####


####################################################################PROMPT####################################################################
#####ACLS_COMMAND_LINE_EXAMPLE#####
  - name: ACLS
    debug:
      msg: "example : ip access-list extended 110, deny icmp 192.0.2.0 0.0.0.255 192.0.3.0 0.0.0.255 echo dscp ef ttl eq 10, permit ip host 2.2.2.2 host 3.3.3.3"
#####ACLS_COMMAND_LINE_EXAMPLE#####

#####ACLS_COMMAND_LINE#####
  - name: ACLS
    pause:
      prompt: "[???] Write your ACLs command here : "
    register: ACLS_COMMAND_LINE
#####ACLS_COMMAND_LINE#####

#####ACLS_LINE_CREATOR#####
  - name: Apply the ACLs configuration
    cisco.ios.ios_command:
      commands: "{{ ACLS_COMMAND_LINE.user_input }}"
#####ACLS_LINE_CREATOR#####
