                                                            #      #####    #       #####
                                                           # #     #        #       #
                                                          #   #    #        #       ##### 
                                                          #####    #        #           # 
                                                          #   #    #####    ####    #####
                                                          

#------------------------------------------#INFORMATION#------------------------------------------#
  - name: INFORMATION
    debug:
      msg: "This role will collect information about ACLS from {{ inventory_hostname }} to help you !"
#------------------------------------------#INFORMATION#------------------------------------------#

#------------------------------------------#RECAP#------------------------------------------#

  - name: 🚦 ACLS | Gather configuration from target device
    cisco.ios.ios_acls:
      state: gathered
    register: ACLS
#  - name: Gather Existing ACLS
#    cisco.ios.ios_command:
#      commands:
#        - show access-lists
#    register: ACLS

  - name: 🚦 ACLS | List ACLS
    debug:
      var: ACLS
#------------------------------------------#RECAP#------------------------------------------#
