
#########################################INFORMATION#########################################

  - name: INFORMATION
    debug:
       msg: "This role will collect information about ACLS from {{ inventory_hostname }} to help you !"

#########################################INFORMATION#########################################

#########################################GATHER#########################################


#########################################GATHER#########################################

#########################################CONVERT#########################################

  - name: Convert Interfaces facts in List
    set_fact:
      interfaces_fact: "{{ interfaces_.ansible_facts.ansible_network_resources.interfaces | map(attribute='name') | list }}"
#########################################CONVERT#########################################
