
---

  - name: INFORMATION
    debug:
      msg: " Starting the ACLS creator engine ... "

######################################GATHER######################################

  - include_tasks: get_info_acls.yml
    
######################################GATHER######################################
