
---
######################################INFORMATION######################################
  - name: INFORMATION
    debug:
      msg:  Starting gathering facts ... 
######################################INFORMATION######################################

######################################GATHER######################################
  - include_tasks: get_info_acls.yml    
######################################GATHER######################################

######################################PROMPT######################################
  - name: ACLS
    pause:
      prompt: "[???] Do you want to launch the ACLS Destructor ? (yes/no)"
    register: ACLS_DESTRUCTOR_CHOICE

  - name: ACLS
    pause:
      prompt: "[???] Do you want to launch the ACLS Creator ? (yes/no)"
    register: ACLS_CREATOR_CHOICE

  - name: ACLS
    pause:
      prompt: "[???] Do you want to launch the ACLS Creator with PROMPT or in LINE ? (promptV1/line (promptV1 is limited) )"
    register: ACLS_CREATOR_TYPE_CHOICE
    when: ACLS_CREATOR_CHOICE.user_input | bool
######################################PROMPT######################################

######################################ACLS_DESTRUCTOR######################################
  - name: INFORMATION
    debug:
      msg:  Starting the ACLS destructor engine ... 
    when: ACLS_DESTRUCTOR_CHOICE.user_input | bool

  - include_tasks: acls_destructor.yml
    when: ACLS_DESTRUCTOR_CHOICE.user_input | bool
######################################ACLS_DESTRUCTOR######################################

######################################ACLS_CREATOR######################################
  - name: INFORMATION
    debug:
      msg:  "Starting the ACLS creator {{  ACLS_CREATOR_TYPE_CHOICE.user_input }} engine ... "

  - include_tasks: acls_creator_promptV1.yml
    when: ACLS_CREATOR_TYPE_CHOICE.user_input == "promptV1"

  - include_tasks: acls_creator_line.yml
    when: ACLS_CREATOR_TYPE_CHOICE.user_input == "line"
######################################ACLS_CREATOR######################################

