
---

  - name: INFORMATION
    debug:
      msg: " Starting the ACLS creator engine ... "

######################################GATHER######################################

  - include_tasks: get_info_acls.yml
    
######################################GATHER######################################

######################################ACLS_CREATOR######################################

  - include_tasks: acls_creator.yml

######################################ACLS_CREATOR######################################
