
---
######################################INFORMATION######################################
  - name: INFORMATION
    debug:
      msg:  Starting gathering facts ... 
######################################INFORMATION######################################

######################################GATHER######################################
  - include_tasks: get_info_acls.yml    
######################################GATHER######################################

######################################PROMPT######################################
  - name: ACLS
    pause:
      prompt: "[???] Do you want to launch the ACLS Creator ? (yes/no)"
    register: ACLS_CREATOR_CHOICE

######################################PROMPT######################################

######################################INFORMATION######################################
  - name: INFORMATION
    debug:
      msg:  Starting the ACLS creator engine ... 
    when: ACLS_CREATOR_CHOICE.user_input | bool
######################################INFORMATION######################################

######################################ACLS_CREATOR######################################
  - include_tasks: acls_creator.yml
    when: ACLS_CREATOR_CHOICE.user_input | bool
######################################ACLS_CREATOR######################################
