
---
######################################INFORMATION######################################
  - name: [ACLs] INFORMATION
    debug:
      msg:  Starting gathering facts ... 
######################################INFORMATION######################################

######################################GATHER######################################
  - include_tasks: get_info_acls.yml    
######################################GATHER######################################

######################################INFORMATION######################################
  - name: [ACLs] INFORMATION
    debug:
      msg:  Starting the ACLS creator engine ... 
######################################INFORMATION######################################

######################################ACLS_CREATOR######################################
  - include_tasks: acls_creator.yml
######################################ACLS_CREATOR######################################
