- name: Verify connection
  win_ping:

- name: Gather system information
  ansible.builtin.setup:
  register: setup_facts

- name: Get info for all installed services
  ansible.windows.win_service_info:
  register: service_info

- name: Run systeminfo command
  win_command: systeminfo
  register: system_info

- name: Show setup facts
  debug:
      var: setup_facts

- name: Show service information
  debug:
      var: service_info

- name: Show system information
  debug:
      var: system_info.stdout_lines

- name: Extract OS name
  set_fact:
    os_name: "{{ system_info.stdout_lines[2] | regex_replace('^Nom du système d’exploitation: +', '') }}"

- name: Show OS NAME
  debug:
      var: os_name
