#-----------------------------#FACTS#-----------------------------#
    - include_tasks: gather_facts.yml
#-----------------------------#FACTS#-----------------------------#

#-----------------------------#PACKAGES#-----------------------------#
    - include_tasks: Packages_Installation/main.yml
#-----------------------------#PACKAGES#-----------------------------#
