#-----------------------------#FACTS#-----------------------------#
    - include_tasks: gather_facts.yml
#-----------------------------#FACTS#-----------------------------#

#-----------------------------#COMMAND#-----------------------------#
    - name: COMMAND
      pause:
        prompt: "[???] Would you like to execute a command ? (yes/no)"
      register: COMMAND_CHOICE
      
    - include_tasks: Command/main.yml
      when: COMMAND_CHOICE.user_input | bool
#-----------------------------#COMMAND#-----------------------------#

#-----------------------------#UPDATES#-----------------------------#
    - name: UPDATES
      pause:
        prompt: "[???] Would you like to updates windows ? (yes/no)"
      register: UPDATES_CHOICE
      
    - include_tasks: Updates/main.yml
      when: UPDATES_CHOICE.user_input | bool
#-----------------------------#UPDATES#-----------------------------#

#-----------------------------#PACKAGES#-----------------------------#
    - name: PACKAGE
      pause:
        prompt: "[???] Would you like to install or update some packages ? (yes/no)"
      register: PACKAGES_CHOICE

    - include_tasks: Packages_Installation/main.yml
      when: PACKAGES_CHOICE.user_input | bool
#-----------------------------#PACKAGES#-----------------------------#

#-----------------------------#SERVICE#-----------------------------#
    - name: SERVICE
      pause:
        prompt: "[???] Would you like to install and configure services ? (yes/no)"
      register: SERVICE_CHOICE

    - include_tasks: Service/main.yml
      when: SERVICE_CHOICE.user_input | bool
#-----------------------------#SERVICE#-----------------------------#

#-----------------------------#REBOOT#-----------------------------#
    - name: REBOOT
      pause:
        prompt: "[???] Do you want to do a reboot ? (yes/no)"
      register: REBOOT_CHOICE

    - include_tasks: Reboot/main.yml
      when: REBOOT_CHOICE.user_input | bool
#-----------------------------#REBOOT#-----------------------------#
