#-----------------------------#FACTS#-----------------------------#
    - include_tasks: gather_facts.yml
#-----------------------------#FACTS#-----------------------------#

#-----------------------------#UPDATES#-----------------------------#
    - include_tasks: Updates/main.yml
#-----------------------------#UPDATES#-----------------------------#

#-----------------------------#PACKAGES#-----------------------------#
    - include_tasks: Packages_Installation/main.yml
#-----------------------------#PACKAGES#-----------------------------#
