#-----------------------------#FACTS#-----------------------------#
    - include_tasks: gather_facts.yml
#-----------------------------#FACTS#-----------------------------#

#-----------------------------#UPDATES#-----------------------------#
    - name: UPDATES
      pause:
        prompt: "[???] Would you like to updates windows ? (yes/no)"
      register: UPDATES_CHOICE
      
    - include_tasks: Updates/main.yml
      when: UPDATES_CHOICE.user_input | bool
#-----------------------------#UPDATES#-----------------------------#

#-----------------------------#PACKAGES#-----------------------------#
    - name: PACKAGE
      pause:
        prompt: "[???] Would you like to install some packages ? (yes/no)"
      register: PACKAGES_CHOICE

    - include_tasks: Packages_Installation/main.yml
      when: PACKAGES_CHOICE.user_input | bool
#-----------------------------#PACKAGES#-----------------------------#
