- name: Search and download Windows updates without installing them
  ansible.windows.win_updates:
    state: downloaded

- name: Install all updates and reboot as many times as needed
  ansible.windows.win_updates:
    category_names: '*'
    reboot: false
