
#------------------------------------------#INFORMATION#------------------------------------------#
  - name: INFORMATION
    debug:
      msg: "This role will collect information about VLAN from {{ inventory_hostname }} to help you !"
#------------------------------------------#INFORMATION#------------------------------------------#

#------------------------------------------#RECAP#------------------------------------------#
  - name: 🔀 VLAN | Gather configuration from target device
    cisco.ios.ios_command:
      commands:
        - show vlan
    register: VLANS_current

  - name: 🔀 VLAN | List VLANs
    debug:
      var: VLANS_current.stdout_lines
#------------------------------------------#RECAP#------------------------------------------#
