#------------------------------------------#VLAN#------------------------------------------#
  - name: VLAN | Command Line 1
    debug:
      msg: "{{ VLAN_LINE_1.user_input }}"
    when: VLAN_LINE_1 is defined

#------------------------------------------#VLAN#------------------------------------------#
