
#------------------------------------------#VLAN#------------------------------------------#
#####VLAN_LINES#####
  - name: VLAN | QUESTION - Lines
    pause:
      prompt: "[???] How many lines do you whant to configure ?"
    register: VLAN_LINES
#####VLAN_LINES#####
#------------------------------------------#VLAN#------------------------------------------#

#------------------------------------------#VALIDATION------------------------------------------#
  - name: VLAN | VALIDATION 
    pause:
      prompt: "[???] Do you want to apply your configuration ? (yes/no)"
    register: VLAN_VALID_CHECK
#------------------------------------------#VALIDATION------------------------------------------#

#------------------------------------------#VLAN#------------------------------------------#
#####APPLY-CONFIGURATION#####
  - name: VLAN | Apply the new VLAN configuration
    cisco.ios.ios_vlans:
      config:
        - name: "{{ VLAN_NAME.user_input }}"
          vlan_id: "{{ VLAN_ID.user_input }}"
          state: active
          shutdown: "{{ VLAN_SHUTDOWN.user_input }}"
#          mtu: "{{ VLAN_MTU.user_input }}"
#          remote_span: "{{ VLAN_REMOTE_SPAN.user_input }}"
      state: "{{ VLAN_STATE.user_input }}"
#####APPLY-CONFIGURATION#####

  - include_tasks: vlan_creator_prompt_reask.yml
#------------------------------------------#VLAN#------------------------------------------#
