
#------------------------------------------#VLAN#------------------------------------------#
#####VLAN_LINES#####
  - name: VLAN | QUESTION - Lines
    pause:
      prompt: "[???] How many lines do you whant to configure ? (Minimum : 2 | Max : 10)"
    register: VLAN_LINES
#####VLAN_LINES#####

#####VLAN_LINE_1#####
  - name: VLAN | QUESTION - Lines
    pause:
      prompt: "[???] Command Line 1 (example : vlan 12)"
    register: VLAN_LINE_1
    when: VLAN_LINES is defined and VLAN_LINES.user_input in ["2", "3", "4", "5", "6", "7", "8", "9", "10"]
#####VLAN_LINE_1#####

#####VLAN_LINE_2#####
  - name: VLAN | QUESTION - Lines
    pause:
      prompt: "[???] Command Line 2"
    register: VLAN_LINE_2
    when: VLAN_LINES is defined and VLAN_LINES.user_input in ["2", "3", "4", "5", "6", "7", "8", "9", "10"]
#####VLAN_LINE_2#####

#####VLAN_LINE_3#####
  - name: VLAN | QUESTION - Lines
    pause:
      prompt: "[???] Command Line 3"
    register: VLAN_LINE_3
    when: VLAN_LINES is defined and VLAN_LINES.user_input in ["3", "4", "5", "6", "7", "8", "9", "10"]
#####VLAN_LINE_3#####

#####VLAN_LINE_4#####
  - name: VLAN | QUESTION - Lines
    pause:
      prompt: "[???] Command Line 4"
    register: VLAN_LINE_4
    when: VLAN_LINES is defined and VLAN_LINES.user_input in ["4", "5", "6", "7", "8", "9", "10"]
#####VLAN_LINE_4#####

#####VLAN_LINE_5#####
  - name: VLAN | QUESTION - Lines
    pause:
      prompt: "[???] Command Line 5"
    register: VLAN_LINE_5
    when: VLAN_LINES is defined and VLAN_LINES.user_input in ["5", "6", "7", "8", "9", "10"]
#####VLAN_LINE_5#####

#####VLAN_LINE_6#####
  - name: VLAN | QUESTION - Lines
    pause:
      prompt: "[???] Command Line 6"
    register: VLAN_LINE_6
    when: VLAN_LINES is defined and VLAN_LINES.user_input in ["6", "7", "8", "9", "10"]
#####VLAN_LINE_6#####

#####VLAN_LINE_7#####
  - name: VLAN | QUESTION - Lines
    pause:
      prompt: "[???] Command Line 7"
    register: VLAN_LINE_7
    when: VLAN_LINES is defined and VLAN_LINES.user_input in ["7", "8", "9", "10"]
#####VLAN_LINE_7#####

#####VLAN_LINE_8#####
  - name: VLAN | QUESTION - Lines
    pause:
      prompt: "[???] Command Line 8"
    register: VLAN_LINE_8
    when: VLAN_LINES is defined and VLAN_LINES.user_input in ["8", "9", "10"]
#####VLAN_LINE_8#####

#####VLAN_LINE_9#####
  - name: VLAN | QUESTION - Lines
    pause:
      prompt: "[???] Command Line 9"
    register: VLAN_LINE_9
    when: VLAN_LINES is defined and VLAN_LINES.user_input in ["9", "10"]
#####VLAN_LINE_9#####

#####VLAN_LINE_10#####
  - name: VLAN | QUESTION - Lines
    pause:
      prompt: "[???] Command Line 10"
    register: VLAN_LINE_5
    when: VLAN_LINES is defined and VLAN_LINES.user_input in ["10"]
#####VLAN_LINE_10#####
#------------------------------------------#VLAN#------------------------------------------#

#------------------------------------------#VALIDATION------------------------------------------#
  - name: VLAN | VERIFICATION
    pause:
      prompt: "[???] Do you want to check your vars ? (yes/no)"
    register: VLAN_DEBUG_CHECK

  - include_tasks: vlan_debug_commandline.yml
    when: VLAN_DEBUG_CHECK.user_input | bool
  
  - name: VLAN | VALIDATION 
    pause:
      prompt: "[???] Do you want to apply your configuration ? (yes/no)"
    register: VLAN_VALID_CHECK
#------------------------------------------#VALIDATION------------------------------------------#

#------------------------------------------#VLAN#------------------------------------------#
#####APPLY-CONFIGURATION_VLAN_LINES_1|2#####
  - name: VLAN | Apply command lines 1|2
    cisco.ios.ios_config:
      lines:
        - "{{ VLAN_LINE_1.user_input }}"
        - "{{ VLAN_LINE_2.user_input }}"
    when: (VLAN_VALID_CHECK.user_input | bool) and (VLAN_LINES is defined) and (VLAN_LINES.user_input in ["2", "3", "4", "5", "6", "7", "8", "9", "10"])
#####APPLY-CONFIGURATION_VLAN_LINES_1|2#####

#####APPLY-CONFIGURATION_VLAN_LINES_3#####
  - name: VLAN | Apply command line 3
    cisco.ios.ios_config:
      lines:
        - "{{ VLAN_LINE_1.user_input }}"
        - "{{ VLAN_LINE_3.user_input }}"
    when: (VLAN_VALID_CHECK.user_input | bool) and (VLAN_LINES is defined) and (VLAN_LINES.user_input in ["3", "4", "5", "6", "7", "8", "9", "10"])
#####APPLY-CONFIGURATION_VLAN_LINES_3#####

#####APPLY-CONFIGURATION_VLAN_LINES_4#####
  - name: VLAN | Apply command line 4
    cisco.ios.ios_config:
      lines:
        - "{{ VLAN_LINE_1.user_input }}"
        - "{{ VLAN_LINE_4.user_input }}"
    when: (VLAN_VALID_CHECK.user_input | bool) and (VLAN_LINES is defined) and (VLAN_LINES.user_input in ["4", "5", "6", "7", "8", "9", "10"])
#####APPLY-CONFIGURATION_VLAN_LINES_4#####

#####APPLY-CONFIGURATION_VLAN_LINES_5#####
  - name: VLAN | Apply command line 5
    cisco.ios.ios_config:
      lines:
        - "{{ VLAN_LINE_1.user_input }}"
        - "{{ VLAN_LINE_5.user_input }}"
    when: (VLAN_VALID_CHECK.user_input | bool) and (VLAN_LINES is defined) and (VLAN_LINES.user_input in ["5", "6", "7", "8", "9", "10"])
#####APPLY-CONFIGURATION_VLAN_LINES_5#####

#####APPLY-CONFIGURATION_VLAN_LINES_6#####
  - name: VLAN | Apply command line 6
    cisco.ios.ios_config:
      lines:
        - "{{ VLAN_LINE_1.user_input }}"
        - "{{ VLAN_LINE_6.user_input }}"
    when: (VLAN_VALID_CHECK.user_input | bool) and (VLAN_LINES is defined) and (VLAN_LINES.user_input in ["6", "7", "8", "9", "10"])
#####APPLY-CONFIGURATION_VLAN_LINES_6#####

#####APPLY-CONFIGURATION_VLAN_LINES_7#####
  - name: VLAN | Apply command line 7
    cisco.ios.ios_config:
      lines:
        - "{{ VLAN_LINE_1.user_input }}"
        - "{{ VLAN_LINE_7.user_input }}"
    when: (VLAN_VALID_CHECK.user_input | bool) and (VLAN_LINES is defined) and (VLAN_LINES.user_input in ["7", "8", "9", "10"])
#####APPLY-CONFIGURATION_VLAN_LINES_7#####

#####APPLY-CONFIGURATION_VLAN_LINES_8#####
  - name: VLAN | Apply command line 8
    cisco.ios.ios_config:
      lines:
        - "{{ VLAN_LINE_1.user_input }}"
        - "{{ VLAN_LINE_8.user_input }}"
    when: (VLAN_VALID_CHECK.user_input | bool) and (VLAN_LINES is defined) and (VLAN_LINES.user_input in ["8", "9", "10"])
#####APPLY-CONFIGURATION_VLAN_LINES_8#####

#####APPLY-CONFIGURATION_VLAN_LINES_9#####
  - name: VLAN | Apply command line 9
    cisco.ios.ios_config:
      lines:
        - "{{ VLAN_LINE_1.user_input }}"
        - "{{ VLAN_LINE_9.user_input }}"
    when: (VLAN_VALID_CHECK.user_input | bool) and (VLAN_LINES is defined) and (VLAN_LINES.user_input in ["9", "10"])
#####APPLY-CONFIGURATION_VLAN_LINES_9#####

#####APPLY-CONFIGURATION_VLAN_LINES_10#####
  - name: VLAN | Apply command line 10
    cisco.ios.ios_config:
      lines:
        - "{{ VLAN_LINE_1.user_input }}"
        - "{{ VLAN_LINE_10.user_input }}"
    when: (VLAN_VALID_CHECK.user_input | bool) and (VLAN_LINES is defined) and (VLAN_LINES.user_input in ["10"])
#####APPLY-CONFIGURATION_VLAN_LINES_10#####

  - include_tasks: vlan_creator_line_reask.yml
#------------------------------------------#VLAN#------------------------------------------#
