
#------------------------------------------#VLAN#------------------------------------------#
#####VLAN_NAME#####
  - name: VLAN | QUESTION - Name
    pause:
      prompt: "[???] What name do you want to set ?"
    register: VLAN_NAME
#####VLAN_NAME#####

#####VLAN-STATE#####
  - name: VLAN | QUESTION - State
    pause:
      prompt: "[???] Which STATE you want your VLAN to be ? [merged/replaced/overriden/deleted/rendered]"
    register: VLAN_STATE
#####VLAN-STATE#####

#####VLAN-ID#####
  - name: VLAN | QUESTION - ID
    pause:
      prompt: "[???] Which ID you want your VLAN to be ? "
    register: VLAN_ID
#####VLAN-ID#####

#####VLAN-SHUTDOWN#####
  - name: VLAN | QUESTION - Shutdown
    pause:
      prompt: "[???] Do you want to enable Shutdown for your VLAN ? (enabled/disabled)"
    register: VLAN_SHUTDOWN
#####VLAN-SHUTDOWN#####
#------------------------------------------#VLAN#------------------------------------------#

#------------------------------------------#VALIDATION------------------------------------------#
  - name: VLAN | VERIFICATION
    pause:
      prompt: "[???] Do you want to check your vars ? (yes/no)"
    register: VLAN_DEBUG_CHECK

  - name: VLAN | VALIDATION 
    pause:
      prompt: "[???] Do you want to apply your configuration ? (yes/no)"
    register: VLAN_VALID_CHECK

  - include_tasks: vlan_debug_var.yml
    when: VLAN_DEBUG_CHECK.user_input | bool
#------------------------------------------#VALIDATION------------------------------------------#

#------------------------------------------#VLAN#------------------------------------------#
#####APPLY-CONFIGURATION#####
  - name: VLAN | Apply the new VLAN configuration
    cisco.ios.ios_vlans:
      config:
        - name: "{{ VLAN_NAME.user_input }}"
          vlan_id: "{{ VLAN_ID.user_input }}"
          state: active
          shutdown: "{{ VLAN_SHUTDOWN.user_input }}"
#          mtu: "{{ VLAN_MTU.user_input }}"
#          remote_span: "{{ VLAN_REMOTE_SPAN.user_input }}"
      state: "{{ VLAN_STATE.user_input }}"
    when: VLAN_VALID_CHECK.user_input | bool
#####APPLY-CONFIGURATION#####

  - include_tasks: vlan_creator_prompt_reask.yml
#------------------------------------------#VLAN#------------------------------------------#
