---
#------------------------------------------#RESTORE#------------------------------------------#
  - name: RESTORE | Copy backup in the remote host
    ansible.builtin.expect:
      command:  "scp {{ BACKUP_DIRECTORY_PATH }}/{{ inventory_hostname }}_latest.config scp@{{ inventory_hostname }}:{{ inventory_hostname }}_latest.config"
      responses:
        (?i)password: "cisco"
    #no_log: true #Activate this to not see the password !
    ignore_errors: true

  - include_tasks: apply_conf.yml

#------------------------------------------#RESTORE#------------------------------------------#

#------------------------------------------#RECAP#------------------------------------------#
  - name: RESTORE | RECAP
    debug:
      msg: " You have copied and applied the latest backup configuration file to your machine."
#------------------------------------------#RECAP#------------------------------------------#
