
######################################BASICS######################################

  - name: BACKUP
    pause:
      prompt: "[???] Would you like to do a backup of the actual configuration ? (yes/no)"
    register: BACKUP_CHOICE

  - include_tasks: backup_conf.yml
    when: BACKUP_CHOICE.user_input | bool
    
######################################BASICS######################################
