#####ACLS-TTL-gt#####
  - name: ACLS
    pause:
      prompt: "[???] What is the number of packets you want to set for gt ?"
    register: ACLS_TTL_DATA
    when: ACLS_TTL.user_input == "gt"
#####ACLS-TTL-gt#####
