- name: Include the variables
  ansible.builtin.include_vars: /etc/ansible/roles/Learning-Ansible/Cisco_Switch/VARS.yml

- name: Test reachability to Ansible using default vrf
  cisco.ios.ios_ping:
    dest: "{{ ANSIBLE_MANAGER }}"
  register: connection_

- name: Show connection results
  debug:
     var: connection_
