- name: Run "show version" & "show interfaces" on remote nodes.
  cisco.ios.ios_command:
    commands:
      - show version
      - show interfaces

- name: Gather all legacy facts
  cisco.ios.ios_facts:
    gather_subset: 
    - all
  register: all_

- name: Show results
  debug:
     var: all_
