- name: Run "show version" & "show interfaces" on remote nodes.
  cisco.ios.ios_command:
    commands:
      - show version
      - show interfaces
  register: info_

- name: Show info results
  debug:
     var: info_
