- name: Run "show version" & "show interfaces" on remote nodes.
  cisco.ios.ios_command:
    commands:
      - show version
      - show interfaces

- name: Gather only the config and default facts
  cisco.ios.ios_facts:
    gather_subset:
      - config

# Test to see the difference :

- name: Gather all legacy facts
  cisco.ios.ios_facts:
    gather_subset: all