- name: Run "show version" & "show interfaces" on remote nodes.
  cisco.ios.ios_command:
    commands:
      - show version
      - show interfaces
  register: info_

- name: Gather all legacy facts
  cisco.ios.ios_facts:
    gather_subset: 
    - all                        # You can replace this by : [config, default, hardware, interfaces, all]

- name: Show info results
  debug:
     var: info_

- name: Show the hostname
  debug:
     msg: "The name of the hostname is : {{ ansible_net_hostname }}"

- name: Show the IpV4 information
  debug:
     msg: "The name of the hostname is : {{ ansible_net_all_ipv4_addresses }}"
