# Configure the file for your Cisco systems.

CISCO_USER: admin # Configure the User.
CISCO_PASS: admin # Configure the password of the user.

CISCO_SECRET: hello # "Enable" password configuration. --> this will become your 'BECOME password'.
