---
  - name: Security config of all ports
    ios_config:
      lines:
      - switchport port-security
      - switchport port-security maximum 10
      - switchport port-security mac-address sticky
      - switchport port-security violation shutdown
      parents: interface GigabitEthernet4/0

  - name: Security config of port GigabitEthernet4/0
    ios_config:
      lines:
      - switchport port-security
      - switchport port-security maximum 10
      - switchport port-security mac-address sticky
      - switchport port-security violation shutdown
      parents: interface GigabitEthernet4/1

  - name: Security config of port GigabitEthernet4/2
    ios_config:
      lines:
      - switchport port-security
      - switchport port-security maximum 10
      - switchport port-security mac-address sticky
      - switchport port-security violation shutdown
      parents: interface GigabitEthernet4/2

  - name: Security config of port GigabitEthernet4/3
    ios_config:
      lines:
      - switchport port-security
      - switchport port-security maximum 10
      - switchport port-security mac-address sticky
      - switchport port-security violation shutdown
      parents: interface GigabitEthernet4/3

  - name: Security config of port GigabitEthernet5/0
    ios_config:
      lines:
      - switchport port-security
      - switchport port-security maximum 10
      - switchport port-security mac-address sticky
      - switchport port-security violation shutdown
      parents: interface GigabitEthernet5/0

  - name: Security config of port GigabitEthernet5/1
    ios_config:
      lines:
      - switchport port-security
      - switchport port-security maximum 10
      - switchport port-security mac-address sticky
      - switchport port-security violation shutdown
      parents: interface GigabitEthernet5/1

  - name: Security config of port GigabitEthernet5/2
    ios_config:
      lines:
      - switchport port-security
      - switchport port-security maximum 10
      - switchport port-security mac-address sticky
      - switchport port-security violation shutdown
      parents: interface GigabitEthernet5/2

  - name: Security config of port GigabitEthernet5/3
    ios_config:
      lines:
      - switchport port-security
      - switchport port-security maximum 10
      - switchport port-security mac-address sticky
      - switchport port-security violation shutdown
      parents: interface GigabitEthernet5/3

  - name: Security config of port GigabitEthernet6/0
    ios_config:
      lines:
      - switchport port-security
      - switchport port-security maximum 10
      - switchport port-security mac-address sticky
      - switchport port-security violation shutdown
      parents: interface GigabitEthernet6/0

  - name: Security config of port GigabitEthernet6/1
    ios_config:
      lines:
      - switchport port-security
      - switchport port-security maximum 10
      - switchport port-security mac-address sticky
      - switchport port-security violation shutdown
      parents: interface GigabitEthernet6/1
