---
  - name: Security config of all ports
    ios_config:
      lines:
      - switchport port-security
      - switchport port-security maximum 10
      - switchport port-security mac-address sticky
      - switchport port-security violation shutdown
      parents: interface GigabitEthernet2/0
    ignore_errors: true

  - name: Security config of port GigabitEthernet2/1
    ios_config:
      lines:
      - switchport port-security
      - switchport port-security maximum 10
      - switchport port-security mac-address sticky
      - switchport port-security violation shutdown
      parents: interface GigabitEthernet2/1
    ignore_errors: true

  - name: Security config of port GigabitEthernet2/2
    ios_config:
      lines:
      - switchport port-security
      - switchport port-security maximum 10
      - switchport port-security mac-address sticky
      - switchport port-security violation shutdown
      parents: interface GigabitEthernet2/2
    ignore_errors: true

  - name: Security config of port GigabitEthernet2/3
    ios_config:
      lines:
      - switchport port-security
      - switchport port-security maximum 10
      - switchport port-security mac-address sticky
      - switchport port-security violation shutdown
      parents: interface GigabitEthernet2/3
    ignore_errors: true

  - name: Security config of port GigabitEthernet1/1
    ios_config:
      lines:
      - switchport port-security
      - switchport port-security maximum 10
      - switchport port-security mac-address sticky
      - switchport port-security violation shutdown
      parents: interface GigabitEthernet1/1
    ignore_errors: true

  - name: Security config of port GigabitEthernet1/2
    ios_config:
      lines:
      - switchport port-security
      - switchport port-security maximum 10
      - switchport port-security mac-address sticky
      - switchport port-security violation shutdown
      parents: interface GigabitEthernet1/2
    ignore_errors: true

  - name: Security config of port GigabitEthernet1/3
    ios_config:
      lines:
      - switchport port-security
      - switchport port-security maximum 10
      - switchport port-security mac-address sticky
      - switchport port-security violation shutdown
      parents: interface GigabitEthernet1/3
    ignore_errors: true

#  - name: Security config of port GigabitEthernet(*/*)
#    ios_config:
#      lines:
#      - switchport port-security
#      - switchport port-security maximum 10
#      - switchport port-security mac-address sticky
#      - switchport port-security violation shutdown
#      parents: interface GigabitEthernet(*/*)
#    ignore_errors: true

#  - name: Security config of port GigabitEthernet(*/*)
#    ios_config:
#      lines:
#      - switchport port-security
#      - switchport port-security maximum 10
#      - switchport port-security mac-address sticky
#      - switchport port-security violation shutdown
#      parents: interface GigabitEthernet(*/*)
#    ignore_errors: true

#  - name: Security config of port GigabitEthernet(*/*)
#    ios_config:
#      lines:
#      - switchport port-security
#      - switchport port-security maximum 10
#      - switchport port-security mac-address sticky
#      - switchport port-security violation shutdown
#      parents: interface GigabitEthernet(*/*)
#    ignore_errors: true
