- name: CHOCOLATEY
  block:
    - name: Ensure Chocolatey itself is installed, using community repo for the bootstrap
      win_chocolatey:
        name: chocolatey
      when: PACKAGES_CHOICE.user_input == "no"
  rescue:
    - name: Reboot the host to complete the install
      ansible.windows.win_reboot:
        reboot_timeout: 3600
    - name: Verify Chocolatey is installed
      win_chocolatey:
        name: chocolatey

- name: Install NSSM
  win_chocolatey:
    name: nssm
