- name: Ensure Chocolatey itself is installed, using community repo for the bootstrap
  win_chocolatey:
    name: chocolatey
  when: PACKAGES_CHOICE.user_input | bool

- name: Install NSSM
  win_chocolatey:
    name: nssm
