- name: Get info for all installed services
  ansible.windows.win_service_info:
  register: SERVICE_INFO

- name: SERVICE
  pause:
    prompt: "[???] Which service would you like to configure? (ex : OpenSSH)"
  register: SERVICE_NAME_CHOICE

- name: SERVICE
  pause:
    prompt: "[???] In wich state would you like the service to be ? (reloaded/restarted/started/stopped)"
  register: SERVICE_STATE_CHOICE

- name: SERVICE
  pause:
    prompt: "[???] Would you like the service to start automatically ? (yes/no)"
  register: SERVICE_STATE_AUTO_CHOICE
