- name: Install the service
  community.windows.win_nssm:
    name: "{{ SERVICE_NAME_CHOICE.user_input }}"
    state: present

- name: Start service
  ansible.builtin.service:
    name: "{{ SERVICE_NAME_CHOICE.user_input }}"
    state: "{{ SERVICE_STATE_CHOICE.user_input }}"

- name: Set service startup mode to auto
  ansible.windows.win_service:
    name: "{{ SERVICE_NAME_CHOICE.user_input }}"
    start_mode: auto
