---
  - name: Backup config
    ios_config:
      backup: yes
      backup_options: 
#        filename: "{{ inventory_hostname }}.config"
        dir_path: /etc/ansible/roles/Learning-Ansible/Cisco_Switch/Backup
    register: config_output

  - name: Remove none important lines +1
    lineinfile:
      path: "/etc/ansible/roles/Learning-Ansible/Cisco_Switch/Backup/{{ inventory_hostname }}.config"
      regex: 'Building configuration.*'
      state: absent

  - name: Remove none important lines +2
    lineinfile:
      path: "/etc/ansible/roles/Learning-Ansible/Cisco_Switch/Backup/{{ inventory_hostname }}.config"
      regex: 'Current configuration.*'
      state: absent

#  - name: Copy & Rename Backup
#    copy:
#      src: "{{ config_output.backup_path }}"
#      dest: "./backup/{{ inventory_hostname }}.config"
