---
  - name: Execute write memory
    ios_config:
      commands:
        - do write memory

  - name: Get the Running config
    ios_command:
      commands:
        - show run
    register: show_output
    ignore_errors: true

  - name: Display the running config
    debug:
      var: show_output
