---
  - name: Execute write memory
    ios_config:
      commands:
        - do write memory
    register: write_memory

#  - name: Display the write memory result
#    debug:
#      var: write_memory
