- name: Test the PsExec connection to the local system (target node) with your user
  community.windows.win_psexec:
    command: "Get-WindowsFeature -Name *"
  register: COMMAND_RESULT

- name: Show command result
  debug:
      var: COMMAND_RESULT

- name: COMMAND
  pause:
    prompt: "[???] Would you like to run another command ? (yes/no)"
  register: CMD_REASK

- include_tasks: gather_facts.yml
  when: CMD_REASK.user_input | bool
