- name: Verify Psexec is installed
  win_chocolatey:
    name: psexec

- name: Run a PowerShell command
  community.windows.psexec:
    executable: powershell.exe
    arguments: "Get-WindowsFeature -Name *"
  register: COMMAND_RESULT

- name: Show command result
  debug:
      var: COMMAND_RESULT.stdout_lines

- name: COMMAND
  pause:
    prompt: "[???] Would you like to run another command ? (yes/no)"
  register: CMD_REASK

- include_tasks: main.yml
  when: CMD_REASK.user_input | bool
