- name: Run an executable and send data to the stdin for the executable
  ansible.windows.win_command: powershell.exe -
  args:
    stdin: "Get-WindowsFeature -Name *"
  register: COMMAND_RESULT

- name: Show command result
  debug:
      var: COMMAND_RESULT.stdout_lines

- name: COMMAND
  pause:
    prompt: "[???] Would you like to run another command ? (yes/no)"
  register: CMD_REASK

- include_tasks: gather_facts.yml
  when: CMD_REASK.user_input | bool
