- name: Verify Psexec is installed
  win_chocolatey:
    name: psexec

- name: Run the command with Psexec
  community.windows.win_psexec:
    command: "Get-WindowsFeature -Name *"
  register: COMMAND_RESULT

- name: Show command result
  debug:
      var: COMMAND_RESULT.stdout_lines
