- name: Run the command with Powershell
  ansible.windows.win_command: powershell.exe -
  args:
    stdin: "{{ CMD_EXEC.user_input }}"
  register: COMMAND_RESULT

- name: Show command result
  debug:
      var: COMMAND_RESULT.stdout_lines

- name: COMMAND
  pause:
    prompt: "[???] Would you like to run another command ? (yes/no)"
  register: CMD_REASK

- include_tasks: main.yml
  when: CMD_REASK.user_input | bool
