#------------------------------------------#DEBUG#------------------------------------------#

  - name: 🐞 DEBUG | QUESTION
    pause:
      prompt: "[???] Would you like to do a debug before any action ? (yes/no)"
    register: DEBUG_CHOICE

  - include_tasks: debug_conf.yml
    when: DEBUG_CHOICE.user_input | bool
    
#------------------------------------------#DEBUG#------------------------------------------#
