- name: Install Nmap
  ansible.builtin.package:
    name:
      - nmap
    state: present

- name: Install Net-Tools
  ansible.builtin.package:
    name:
      - net-tools
    state: present

- name: Install WGet
  ansible.builtin.package:
    name:
      - wget
    state: present

- name: Install Curl
  ansible.builtin.package:
    name:
      - curl
    state: present

- name: Install OpenSSH-Server
  ansible.builtin.package:
    name:
      - openssh-server
    state: present

- name: Install WireShark
  ansible.builtin.package:
    name:
      - wireshark
    state: present

- name: Install Git
  ansible.builtin.package:
    name:
      - git
    state: present

- name: Install Locate
  ansible.builtin.package:
    name:
      - mlocate
    state: present

- name: Install Tor
  ansible.builtin.package:
    name:
      - tor
    state: present

- name: Install Torcs (Cars Game)
  ansible.builtin.package:
    name:
      - torcs
    state: present

- name: Install Pip
  ansible.builtin.package:
    name:
      - python3-pip
      - pipx
    state: present

- name: Install Tar
  ansible.builtin.package:
    name:
      - tar
    state: present
